// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cache.proto
// Protobuf C++ Version: 6.33.5

#ifndef cache_2eproto_2epb_2eh
#define cache_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cache_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cache_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cache_2eproto;
}  // extern "C"
class PlaylistCacheEntry;
struct PlaylistCacheEntryDefaultTypeInternal;
extern PlaylistCacheEntryDefaultTypeInternal _PlaylistCacheEntry_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlaylistCacheEntry_class_data_;
class PlaylistCacheHead;
struct PlaylistCacheHeadDefaultTypeInternal;
extern PlaylistCacheHeadDefaultTypeInternal _PlaylistCacheHead_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlaylistCacheHead_class_data_;
class PlaylistCacheNode;
struct PlaylistCacheNodeDefaultTypeInternal;
extern PlaylistCacheNodeDefaultTypeInternal _PlaylistCacheNode_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlaylistCacheNode_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PlaylistCacheHead final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PlaylistCacheHead) */ {
 public:
  inline PlaylistCacheHead() : PlaylistCacheHead(nullptr) {}
  ~PlaylistCacheHead() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlaylistCacheHead* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlaylistCacheHead));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlaylistCacheHead(::google::protobuf::internal::ConstantInitialized);

  inline PlaylistCacheHead(const PlaylistCacheHead& from) : PlaylistCacheHead(nullptr, from) {}
  inline PlaylistCacheHead(PlaylistCacheHead&& from) noexcept
      : PlaylistCacheHead(nullptr, ::std::move(from)) {}
  inline PlaylistCacheHead& operator=(const PlaylistCacheHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlaylistCacheHead& operator=(PlaylistCacheHead&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlaylistCacheHead& default_instance() {
    return *reinterpret_cast<const PlaylistCacheHead*>(
        &_PlaylistCacheHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PlaylistCacheHead& a, PlaylistCacheHead& b) { a.Swap(&b); }
  inline void Swap(PlaylistCacheHead* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlaylistCacheHead* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlaylistCacheHead* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlaylistCacheHead>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlaylistCacheHead& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlaylistCacheHead& from) { PlaylistCacheHead::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlaylistCacheHead* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PlaylistCacheHead"; }

  explicit PlaylistCacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlaylistCacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlaylistCacheHead& from);
  PlaylistCacheHead(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlaylistCacheHead&& from) noexcept
      : PlaylistCacheHead(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIsSortedFieldNumber = 100,
  };
  // bool is_sorted = 100;
  bool has_is_sorted() const;
  void clear_is_sorted() ;
  bool is_sorted() const;
  void set_is_sorted(bool value);

  private:
  bool _internal_is_sorted() const;
  void _internal_set_is_sorted(bool value);

  public:
  // @@protoc_insertion_point(class_scope:PlaylistCacheHead)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlaylistCacheHead& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool is_sorted_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlaylistCacheHead_class_data_;
// -------------------------------------------------------------------

class PlaylistCacheEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PlaylistCacheEntry) */ {
 public:
  inline PlaylistCacheEntry() : PlaylistCacheEntry(nullptr) {}
  ~PlaylistCacheEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlaylistCacheEntry* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlaylistCacheEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlaylistCacheEntry(::google::protobuf::internal::ConstantInitialized);

  inline PlaylistCacheEntry(const PlaylistCacheEntry& from) : PlaylistCacheEntry(nullptr, from) {}
  inline PlaylistCacheEntry(PlaylistCacheEntry&& from) noexcept
      : PlaylistCacheEntry(nullptr, ::std::move(from)) {}
  inline PlaylistCacheEntry& operator=(const PlaylistCacheEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlaylistCacheEntry& operator=(PlaylistCacheEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlaylistCacheEntry& default_instance() {
    return *reinterpret_cast<const PlaylistCacheEntry*>(
        &_PlaylistCacheEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PlaylistCacheEntry& a, PlaylistCacheEntry& b) { a.Swap(&b); }
  inline void Swap(PlaylistCacheEntry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlaylistCacheEntry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlaylistCacheEntry* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlaylistCacheEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlaylistCacheEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlaylistCacheEntry& from) { PlaylistCacheEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlaylistCacheEntry* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PlaylistCacheEntry"; }

  explicit PlaylistCacheEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlaylistCacheEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlaylistCacheEntry& from);
  PlaylistCacheEntry(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlaylistCacheEntry&& from) noexcept
      : PlaylistCacheEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kEtagFieldNumber = 2,
    kTitleFieldNumber = 3,
    kIdHashFieldNumber = 6,
    kIsPrivateFieldNumber = 4,
    kItemsFieldNumber = 5,
  };
  // string id = 1;
  bool has_id() const;
  void clear_id() ;
  ::absl::string_view id() const;
  template <typename Arg_ = ::std::string&&>
  void set_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(::absl::string_view value);

  public:
  // string etag = 2;
  bool has_etag() const;
  void clear_etag() ;
  ::absl::string_view etag() const;
  template <typename Arg_ = ::std::string&&>
  void set_etag(Arg_&& arg);

  private:
  ::absl::string_view _internal_etag() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_etag(::absl::string_view value);

  public:
  // string title = 3;
  bool has_title() const;
  void clear_title() ;
  ::absl::string_view title() const;
  template <typename Arg_ = ::std::string&&>
  void set_title(Arg_&& arg);

  private:
  ::absl::string_view _internal_title() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_title(::absl::string_view value);

  public:
  // bytes id_hash = 6;
  bool has_id_hash() const;
  void clear_id_hash() ;
  ::absl::string_view id_hash() const;
  template <typename Arg_ = ::std::string&&>
  void set_id_hash(Arg_&& arg);

  private:
  ::absl::string_view _internal_id_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id_hash(::absl::string_view value);

  public:
  // bool is_private = 4;
  bool has_is_private() const;
  void clear_is_private() ;
  bool is_private() const;
  void set_is_private(bool value);

  private:
  bool _internal_is_private() const;
  void _internal_set_is_private(bool value);

  public:
  // int32 items = 5;
  bool has_items() const;
  void clear_items() ;
  ::int32_t items() const;
  void set_items(::int32_t value);

  private:
  ::int32_t _internal_items() const;
  void _internal_set_items(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:PlaylistCacheEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 38,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlaylistCacheEntry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr etag_;
    ::google::protobuf::internal::ArenaStringPtr title_;
    ::google::protobuf::internal::ArenaStringPtr id_hash_;
    bool is_private_;
    ::int32_t items_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlaylistCacheEntry_class_data_;
// -------------------------------------------------------------------

class PlaylistCacheNode final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PlaylistCacheNode) */ {
 public:
  inline PlaylistCacheNode() : PlaylistCacheNode(nullptr) {}
  ~PlaylistCacheNode() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlaylistCacheNode* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlaylistCacheNode));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlaylistCacheNode(::google::protobuf::internal::ConstantInitialized);

  inline PlaylistCacheNode(const PlaylistCacheNode& from) : PlaylistCacheNode(nullptr, from) {}
  inline PlaylistCacheNode(PlaylistCacheNode&& from) noexcept
      : PlaylistCacheNode(nullptr, ::std::move(from)) {}
  inline PlaylistCacheNode& operator=(const PlaylistCacheNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlaylistCacheNode& operator=(PlaylistCacheNode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlaylistCacheNode& default_instance() {
    return *reinterpret_cast<const PlaylistCacheNode*>(
        &_PlaylistCacheNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PlaylistCacheNode& a, PlaylistCacheNode& b) { a.Swap(&b); }
  inline void Swap(PlaylistCacheNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlaylistCacheNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlaylistCacheNode* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlaylistCacheNode>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlaylistCacheNode& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlaylistCacheNode& from) { PlaylistCacheNode::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlaylistCacheNode* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PlaylistCacheNode"; }

  explicit PlaylistCacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlaylistCacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlaylistCacheNode& from);
  PlaylistCacheNode(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlaylistCacheNode&& from) noexcept
      : PlaylistCacheNode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextFieldNumber = 2,
    kEntryFieldNumber = 1,
  };
  // string next = 2;
  bool has_next() const;
  void clear_next() ;
  ::absl::string_view next() const;
  template <typename Arg_ = ::std::string&&>
  void set_next(Arg_&& arg);

  private:
  ::absl::string_view _internal_next() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_next(::absl::string_view value);

  public:
  // .PlaylistCacheEntry entry = 1;
  bool has_entry() const;
  void clear_entry() ;
  const ::PlaylistCacheEntry& entry() const;
  [[nodiscard]] ::PlaylistCacheEntry* PROTOBUF_NULLABLE release_entry();
  ::PlaylistCacheEntry* PROTOBUF_NONNULL mutable_entry();
  void set_allocated_entry(::PlaylistCacheEntry* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_entry(::PlaylistCacheEntry* PROTOBUF_NULLABLE value);
  ::PlaylistCacheEntry* PROTOBUF_NULLABLE unsafe_arena_release_entry();

  private:
  const ::PlaylistCacheEntry& _internal_entry() const;
  ::PlaylistCacheEntry* PROTOBUF_NONNULL _internal_mutable_entry();

  public:
  // @@protoc_insertion_point(class_scope:PlaylistCacheNode)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 30,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlaylistCacheNode& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr next_;
    ::PlaylistCacheEntry* PROTOBUF_NULLABLE entry_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlaylistCacheNode_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlaylistCacheEntry

// string id = 1;
inline bool PlaylistCacheEntry::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PlaylistCacheEntry::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view PlaylistCacheEntry::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlaylistCacheEntry.id)
  return _internal_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistCacheEntry::set_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:PlaylistCacheEntry.id)
}
inline ::absl::string_view PlaylistCacheEntry::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void PlaylistCacheEntry::_internal_set_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(value, GetArena());
}

// string etag = 2;
inline bool PlaylistCacheEntry::has_etag() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void PlaylistCacheEntry::clear_etag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.etag_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view PlaylistCacheEntry::etag() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlaylistCacheEntry.etag)
  return _internal_etag();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistCacheEntry::set_etag(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.etag_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:PlaylistCacheEntry.etag)
}
inline ::absl::string_view PlaylistCacheEntry::_internal_etag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.etag_.Get();
}
inline void PlaylistCacheEntry::_internal_set_etag(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.etag_.Set(value, GetArena());
}

// string title = 3;
inline bool PlaylistCacheEntry::has_title() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void PlaylistCacheEntry::clear_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::absl::string_view PlaylistCacheEntry::title() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlaylistCacheEntry.title)
  return _internal_title();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistCacheEntry::set_title(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.title_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:PlaylistCacheEntry.title)
}
inline ::absl::string_view PlaylistCacheEntry::_internal_title() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_.Get();
}
inline void PlaylistCacheEntry::_internal_set_title(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.title_.Set(value, GetArena());
}

// bool is_private = 4;
inline bool PlaylistCacheEntry::has_is_private() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void PlaylistCacheEntry::clear_is_private() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_private_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool PlaylistCacheEntry::is_private() const {
  // @@protoc_insertion_point(field_get:PlaylistCacheEntry.is_private)
  return _internal_is_private();
}
inline void PlaylistCacheEntry::set_is_private(bool value) {
  _internal_set_is_private(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:PlaylistCacheEntry.is_private)
}
inline bool PlaylistCacheEntry::_internal_is_private() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_private_;
}
inline void PlaylistCacheEntry::_internal_set_is_private(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_private_ = value;
}

// int32 items = 5;
inline bool PlaylistCacheEntry::has_items() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void PlaylistCacheEntry::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t PlaylistCacheEntry::items() const {
  // @@protoc_insertion_point(field_get:PlaylistCacheEntry.items)
  return _internal_items();
}
inline void PlaylistCacheEntry::set_items(::int32_t value) {
  _internal_set_items(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:PlaylistCacheEntry.items)
}
inline ::int32_t PlaylistCacheEntry::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_;
}
inline void PlaylistCacheEntry::_internal_set_items(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_ = value;
}

// bytes id_hash = 6;
inline bool PlaylistCacheEntry::has_id_hash() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void PlaylistCacheEntry::clear_id_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_hash_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::absl::string_view PlaylistCacheEntry::id_hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlaylistCacheEntry.id_hash)
  return _internal_id_hash();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistCacheEntry::set_id_hash(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.id_hash_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:PlaylistCacheEntry.id_hash)
}
inline ::absl::string_view PlaylistCacheEntry::_internal_id_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_hash_.Get();
}
inline void PlaylistCacheEntry::_internal_set_id_hash(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.id_hash_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// PlaylistCacheNode

// .PlaylistCacheEntry entry = 1;
inline bool PlaylistCacheNode::has_entry() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.entry_ != nullptr);
  return value;
}
inline void PlaylistCacheNode::clear_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.entry_ != nullptr) _impl_.entry_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::PlaylistCacheEntry& PlaylistCacheNode::_internal_entry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::PlaylistCacheEntry* p = _impl_.entry_;
  return p != nullptr ? *p : reinterpret_cast<const ::PlaylistCacheEntry&>(::_PlaylistCacheEntry_default_instance_);
}
inline const ::PlaylistCacheEntry& PlaylistCacheNode::entry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlaylistCacheNode.entry)
  return _internal_entry();
}
inline void PlaylistCacheNode::unsafe_arena_set_allocated_entry(
    ::PlaylistCacheEntry* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.entry_);
  }
  _impl_.entry_ = reinterpret_cast<::PlaylistCacheEntry*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:PlaylistCacheNode.entry)
}
inline ::PlaylistCacheEntry* PROTOBUF_NULLABLE PlaylistCacheNode::release_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::PlaylistCacheEntry* released = _impl_.entry_;
  _impl_.entry_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::PlaylistCacheEntry* PROTOBUF_NULLABLE PlaylistCacheNode::unsafe_arena_release_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:PlaylistCacheNode.entry)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::PlaylistCacheEntry* temp = _impl_.entry_;
  _impl_.entry_ = nullptr;
  return temp;
}
inline ::PlaylistCacheEntry* PROTOBUF_NONNULL PlaylistCacheNode::_internal_mutable_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.entry_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::PlaylistCacheEntry>(GetArena());
    _impl_.entry_ = reinterpret_cast<::PlaylistCacheEntry*>(p);
  }
  return _impl_.entry_;
}
inline ::PlaylistCacheEntry* PROTOBUF_NONNULL PlaylistCacheNode::mutable_entry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::PlaylistCacheEntry* _msg = _internal_mutable_entry();
  // @@protoc_insertion_point(field_mutable:PlaylistCacheNode.entry)
  return _msg;
}
inline void PlaylistCacheNode::set_allocated_entry(::PlaylistCacheEntry* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.entry_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.entry_ = reinterpret_cast<::PlaylistCacheEntry*>(value);
  // @@protoc_insertion_point(field_set_allocated:PlaylistCacheNode.entry)
}

// string next = 2;
inline bool PlaylistCacheNode::has_next() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PlaylistCacheNode::clear_next() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view PlaylistCacheNode::next() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PlaylistCacheNode.next)
  return _internal_next();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistCacheNode::set_next(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.next_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:PlaylistCacheNode.next)
}
inline ::absl::string_view PlaylistCacheNode::_internal_next() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.next_.Get();
}
inline void PlaylistCacheNode::_internal_set_next(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.next_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// PlaylistCacheHead

// bool is_sorted = 100;
inline bool PlaylistCacheHead::has_is_sorted() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PlaylistCacheHead::clear_is_sorted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_sorted_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool PlaylistCacheHead::is_sorted() const {
  // @@protoc_insertion_point(field_get:PlaylistCacheHead.is_sorted)
  return _internal_is_sorted();
}
inline void PlaylistCacheHead::set_is_sorted(bool value) {
  _internal_set_is_sorted(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:PlaylistCacheHead.is_sorted)
}
inline bool PlaylistCacheHead::_internal_is_sorted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_sorted_;
}
inline void PlaylistCacheHead::_internal_set_is_sorted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_sorted_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cache_2eproto_2epb_2eh
