edition = "2024";

package proto;

message CacheHead {
	string next = 1;
	string etag = 2;
	uint32 sid_len = 3;
}

message Playlist {
	string id = 1;
	string etag = 2;
	string version = 3;
	string title = 4;
	bool is_private = 5;
	int32 items = 6;
	string short_id = 7;
	string items_id = 8;
	string items_etag = 9;
}

message CacheNode {
	string next = 1;
	string prev = 2;
	Playlist playlist = 3;
	string items_id = 4;
	bytes id_hash = 5;
}

enum Platform {
	YOUTUBE = 0;
	SPOTIFY = 1;
	INVALID = 2;
}

message PairPlatformPlaylist {
	Platform plat = 1;
	Playlist playlist = 2;
}

message PlaylistItems {
	repeated PairPlatformPlaylist tracked = 1;
	repeated bytes song_hashes = 2;
}

message SidToIdMap {
	message Pair {
		bytes short_id = 1;
		string id = 2;
	}

	message Bucket {
		repeated Pair pairs = 1;
	}

	// map type exists but doing it manually for fun
	repeated Bucket buckets = 1;
}
