// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cache.proto
// Protobuf C++ Version: 6.33.5

#ifndef cache_2eproto_2epb_2eh
#define cache_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_cache_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_cache_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_cache_2eproto;
}  // extern "C"
class MetaCacheEntry;
struct MetaCacheEntryDefaultTypeInternal;
extern MetaCacheEntryDefaultTypeInternal _MetaCacheEntry_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MetaCacheEntry_class_data_;
class MetaCacheHead;
struct MetaCacheHeadDefaultTypeInternal;
extern MetaCacheHeadDefaultTypeInternal _MetaCacheHead_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MetaCacheHead_class_data_;
class MetaCacheNode;
struct MetaCacheNodeDefaultTypeInternal;
extern MetaCacheNodeDefaultTypeInternal _MetaCacheNode_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MetaCacheNode_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class MetaCacheHead final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MetaCacheHead) */ {
 public:
  inline MetaCacheHead() : MetaCacheHead(nullptr) {}
  ~MetaCacheHead() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MetaCacheHead* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MetaCacheHead));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MetaCacheHead(::google::protobuf::internal::ConstantInitialized);

  inline MetaCacheHead(const MetaCacheHead& from) : MetaCacheHead(nullptr, from) {}
  inline MetaCacheHead(MetaCacheHead&& from) noexcept
      : MetaCacheHead(nullptr, ::std::move(from)) {}
  inline MetaCacheHead& operator=(const MetaCacheHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetaCacheHead& operator=(MetaCacheHead&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetaCacheHead& default_instance() {
    return *reinterpret_cast<const MetaCacheHead*>(
        &_MetaCacheHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(MetaCacheHead& a, MetaCacheHead& b) { a.Swap(&b); }
  inline void Swap(MetaCacheHead* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetaCacheHead* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetaCacheHead* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MetaCacheHead>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MetaCacheHead& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MetaCacheHead& from) { MetaCacheHead::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MetaCacheHead* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MetaCacheHead"; }

  explicit MetaCacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MetaCacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MetaCacheHead& from);
  MetaCacheHead(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MetaCacheHead&& from) noexcept
      : MetaCacheHead(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIsSortedFieldNumber = 100,
  };
  // bool is_sorted = 100;
  bool has_is_sorted() const;
  void clear_is_sorted() ;
  bool is_sorted() const;
  void set_is_sorted(bool value);

  private:
  bool _internal_is_sorted() const;
  void _internal_set_is_sorted(bool value);

  public:
  // @@protoc_insertion_point(class_scope:MetaCacheHead)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   7>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MetaCacheHead& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool is_sorted_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MetaCacheHead_class_data_;
// -------------------------------------------------------------------

class MetaCacheEntry final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MetaCacheEntry) */ {
 public:
  inline MetaCacheEntry() : MetaCacheEntry(nullptr) {}
  ~MetaCacheEntry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MetaCacheEntry* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MetaCacheEntry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MetaCacheEntry(::google::protobuf::internal::ConstantInitialized);

  inline MetaCacheEntry(const MetaCacheEntry& from) : MetaCacheEntry(nullptr, from) {}
  inline MetaCacheEntry(MetaCacheEntry&& from) noexcept
      : MetaCacheEntry(nullptr, ::std::move(from)) {}
  inline MetaCacheEntry& operator=(const MetaCacheEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetaCacheEntry& operator=(MetaCacheEntry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetaCacheEntry& default_instance() {
    return *reinterpret_cast<const MetaCacheEntry*>(
        &_MetaCacheEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MetaCacheEntry& a, MetaCacheEntry& b) { a.Swap(&b); }
  inline void Swap(MetaCacheEntry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetaCacheEntry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetaCacheEntry* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MetaCacheEntry>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MetaCacheEntry& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MetaCacheEntry& from) { MetaCacheEntry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MetaCacheEntry* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MetaCacheEntry"; }

  explicit MetaCacheEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MetaCacheEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MetaCacheEntry& from);
  MetaCacheEntry(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MetaCacheEntry&& from) noexcept
      : MetaCacheEntry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kEtagFieldNumber = 2,
    kTitleFieldNumber = 3,
    kIdHashFieldNumber = 6,
    kIsPrivateFieldNumber = 4,
    kItemsFieldNumber = 5,
  };
  // string id = 1;
  bool has_id() const;
  void clear_id() ;
  ::absl::string_view id() const;
  template <typename Arg_ = ::std::string&&>
  void set_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(::absl::string_view value);

  public:
  // string etag = 2;
  bool has_etag() const;
  void clear_etag() ;
  ::absl::string_view etag() const;
  template <typename Arg_ = ::std::string&&>
  void set_etag(Arg_&& arg);

  private:
  ::absl::string_view _internal_etag() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_etag(::absl::string_view value);

  public:
  // string title = 3;
  bool has_title() const;
  void clear_title() ;
  ::absl::string_view title() const;
  template <typename Arg_ = ::std::string&&>
  void set_title(Arg_&& arg);

  private:
  ::absl::string_view _internal_title() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_title(::absl::string_view value);

  public:
  // bytes id_hash = 6;
  bool has_id_hash() const;
  void clear_id_hash() ;
  ::absl::string_view id_hash() const;
  template <typename Arg_ = ::std::string&&>
  void set_id_hash(Arg_&& arg);

  private:
  ::absl::string_view _internal_id_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id_hash(::absl::string_view value);

  public:
  // bool is_private = 4;
  bool has_is_private() const;
  void clear_is_private() ;
  bool is_private() const;
  void set_is_private(bool value);

  private:
  bool _internal_is_private() const;
  void _internal_set_is_private(bool value);

  public:
  // int32 items = 5;
  bool has_items() const;
  void clear_items() ;
  ::int32_t items() const;
  void set_items(::int32_t value);

  private:
  ::int32_t _internal_items() const;
  void _internal_set_items(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:MetaCacheEntry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 34,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MetaCacheEntry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr etag_;
    ::google::protobuf::internal::ArenaStringPtr title_;
    ::google::protobuf::internal::ArenaStringPtr id_hash_;
    bool is_private_;
    ::int32_t items_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MetaCacheEntry_class_data_;
// -------------------------------------------------------------------

class MetaCacheNode final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MetaCacheNode) */ {
 public:
  inline MetaCacheNode() : MetaCacheNode(nullptr) {}
  ~MetaCacheNode() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MetaCacheNode* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MetaCacheNode));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MetaCacheNode(::google::protobuf::internal::ConstantInitialized);

  inline MetaCacheNode(const MetaCacheNode& from) : MetaCacheNode(nullptr, from) {}
  inline MetaCacheNode(MetaCacheNode&& from) noexcept
      : MetaCacheNode(nullptr, ::std::move(from)) {}
  inline MetaCacheNode& operator=(const MetaCacheNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline MetaCacheNode& operator=(MetaCacheNode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MetaCacheNode& default_instance() {
    return *reinterpret_cast<const MetaCacheNode*>(
        &_MetaCacheNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(MetaCacheNode& a, MetaCacheNode& b) { a.Swap(&b); }
  inline void Swap(MetaCacheNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MetaCacheNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MetaCacheNode* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MetaCacheNode>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MetaCacheNode& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MetaCacheNode& from) { MetaCacheNode::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MetaCacheNode* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MetaCacheNode"; }

  explicit MetaCacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MetaCacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MetaCacheNode& from);
  MetaCacheNode(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MetaCacheNode&& from) noexcept
      : MetaCacheNode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPrevFieldNumber = 2,
    kNextFieldNumber = 3,
    kEntryFieldNumber = 1,
  };
  // string prev = 2;
  bool has_prev() const;
  void clear_prev() ;
  ::absl::string_view prev() const;
  template <typename Arg_ = ::std::string&&>
  void set_prev(Arg_&& arg);

  private:
  ::absl::string_view _internal_prev() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_prev(::absl::string_view value);

  public:
  // string next = 3;
  bool has_next() const;
  void clear_next() ;
  ::absl::string_view next() const;
  template <typename Arg_ = ::std::string&&>
  void set_next(Arg_&& arg);

  private:
  ::absl::string_view _internal_next() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_next(::absl::string_view value);

  public:
  // .MetaCacheEntry entry = 1;
  bool has_entry() const;
  void clear_entry() ;
  const ::MetaCacheEntry& entry() const;
  [[nodiscard]] ::MetaCacheEntry* PROTOBUF_NULLABLE release_entry();
  ::MetaCacheEntry* PROTOBUF_NONNULL mutable_entry();
  void set_allocated_entry(::MetaCacheEntry* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_entry(::MetaCacheEntry* PROTOBUF_NULLABLE value);
  ::MetaCacheEntry* PROTOBUF_NULLABLE unsafe_arena_release_entry();

  private:
  const ::MetaCacheEntry& _internal_entry() const;
  ::MetaCacheEntry* PROTOBUF_NONNULL _internal_mutable_entry();

  public:
  // @@protoc_insertion_point(class_scope:MetaCacheNode)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 30,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MetaCacheNode& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr prev_;
    ::google::protobuf::internal::ArenaStringPtr next_;
    ::MetaCacheEntry* PROTOBUF_NULLABLE entry_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_cache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MetaCacheNode_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MetaCacheEntry

// string id = 1;
inline bool MetaCacheEntry::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void MetaCacheEntry::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view MetaCacheEntry::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheEntry.id)
  return _internal_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void MetaCacheEntry::set_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:MetaCacheEntry.id)
}
inline ::absl::string_view MetaCacheEntry::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void MetaCacheEntry::_internal_set_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(value, GetArena());
}

// string etag = 2;
inline bool MetaCacheEntry::has_etag() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void MetaCacheEntry::clear_etag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.etag_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view MetaCacheEntry::etag() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheEntry.etag)
  return _internal_etag();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void MetaCacheEntry::set_etag(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.etag_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:MetaCacheEntry.etag)
}
inline ::absl::string_view MetaCacheEntry::_internal_etag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.etag_.Get();
}
inline void MetaCacheEntry::_internal_set_etag(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.etag_.Set(value, GetArena());
}

// string title = 3;
inline bool MetaCacheEntry::has_title() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void MetaCacheEntry::clear_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::absl::string_view MetaCacheEntry::title() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheEntry.title)
  return _internal_title();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void MetaCacheEntry::set_title(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.title_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:MetaCacheEntry.title)
}
inline ::absl::string_view MetaCacheEntry::_internal_title() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_.Get();
}
inline void MetaCacheEntry::_internal_set_title(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.title_.Set(value, GetArena());
}

// bool is_private = 4;
inline bool MetaCacheEntry::has_is_private() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void MetaCacheEntry::clear_is_private() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_private_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool MetaCacheEntry::is_private() const {
  // @@protoc_insertion_point(field_get:MetaCacheEntry.is_private)
  return _internal_is_private();
}
inline void MetaCacheEntry::set_is_private(bool value) {
  _internal_set_is_private(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:MetaCacheEntry.is_private)
}
inline bool MetaCacheEntry::_internal_is_private() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_private_;
}
inline void MetaCacheEntry::_internal_set_is_private(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_private_ = value;
}

// int32 items = 5;
inline bool MetaCacheEntry::has_items() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void MetaCacheEntry::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t MetaCacheEntry::items() const {
  // @@protoc_insertion_point(field_get:MetaCacheEntry.items)
  return _internal_items();
}
inline void MetaCacheEntry::set_items(::int32_t value) {
  _internal_set_items(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:MetaCacheEntry.items)
}
inline ::int32_t MetaCacheEntry::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_;
}
inline void MetaCacheEntry::_internal_set_items(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_ = value;
}

// bytes id_hash = 6;
inline bool MetaCacheEntry::has_id_hash() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void MetaCacheEntry::clear_id_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_hash_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::absl::string_view MetaCacheEntry::id_hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheEntry.id_hash)
  return _internal_id_hash();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void MetaCacheEntry::set_id_hash(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.id_hash_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:MetaCacheEntry.id_hash)
}
inline ::absl::string_view MetaCacheEntry::_internal_id_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_hash_.Get();
}
inline void MetaCacheEntry::_internal_set_id_hash(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.id_hash_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// MetaCacheNode

// .MetaCacheEntry entry = 1;
inline bool MetaCacheNode::has_entry() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.entry_ != nullptr);
  return value;
}
inline void MetaCacheNode::clear_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.entry_ != nullptr) _impl_.entry_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::MetaCacheEntry& MetaCacheNode::_internal_entry() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::MetaCacheEntry* p = _impl_.entry_;
  return p != nullptr ? *p : reinterpret_cast<const ::MetaCacheEntry&>(::_MetaCacheEntry_default_instance_);
}
inline const ::MetaCacheEntry& MetaCacheNode::entry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheNode.entry)
  return _internal_entry();
}
inline void MetaCacheNode::unsafe_arena_set_allocated_entry(
    ::MetaCacheEntry* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.entry_);
  }
  _impl_.entry_ = reinterpret_cast<::MetaCacheEntry*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:MetaCacheNode.entry)
}
inline ::MetaCacheEntry* PROTOBUF_NULLABLE MetaCacheNode::release_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::MetaCacheEntry* released = _impl_.entry_;
  _impl_.entry_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::MetaCacheEntry* PROTOBUF_NULLABLE MetaCacheNode::unsafe_arena_release_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MetaCacheNode.entry)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::MetaCacheEntry* temp = _impl_.entry_;
  _impl_.entry_ = nullptr;
  return temp;
}
inline ::MetaCacheEntry* PROTOBUF_NONNULL MetaCacheNode::_internal_mutable_entry() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.entry_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::MetaCacheEntry>(GetArena());
    _impl_.entry_ = reinterpret_cast<::MetaCacheEntry*>(p);
  }
  return _impl_.entry_;
}
inline ::MetaCacheEntry* PROTOBUF_NONNULL MetaCacheNode::mutable_entry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::MetaCacheEntry* _msg = _internal_mutable_entry();
  // @@protoc_insertion_point(field_mutable:MetaCacheNode.entry)
  return _msg;
}
inline void MetaCacheNode::set_allocated_entry(::MetaCacheEntry* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.entry_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.entry_ = reinterpret_cast<::MetaCacheEntry*>(value);
  // @@protoc_insertion_point(field_set_allocated:MetaCacheNode.entry)
}

// string prev = 2;
inline bool MetaCacheNode::has_prev() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void MetaCacheNode::clear_prev() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prev_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view MetaCacheNode::prev() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheNode.prev)
  return _internal_prev();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void MetaCacheNode::set_prev(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.prev_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:MetaCacheNode.prev)
}
inline ::absl::string_view MetaCacheNode::_internal_prev() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prev_.Get();
}
inline void MetaCacheNode::_internal_set_prev(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.prev_.Set(value, GetArena());
}

// string next = 3;
inline bool MetaCacheNode::has_next() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void MetaCacheNode::clear_next() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view MetaCacheNode::next() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MetaCacheNode.next)
  return _internal_next();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void MetaCacheNode::set_next(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.next_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:MetaCacheNode.next)
}
inline ::absl::string_view MetaCacheNode::_internal_next() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.next_.Get();
}
inline void MetaCacheNode::_internal_set_next(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.next_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// MetaCacheHead

// bool is_sorted = 100;
inline bool MetaCacheHead::has_is_sorted() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void MetaCacheHead::clear_is_sorted() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_sorted_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool MetaCacheHead::is_sorted() const {
  // @@protoc_insertion_point(field_get:MetaCacheHead.is_sorted)
  return _internal_is_sorted();
}
inline void MetaCacheHead::set_is_sorted(bool value) {
  _internal_set_is_sorted(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:MetaCacheHead.is_sorted)
}
inline bool MetaCacheHead::_internal_is_sorted() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_sorted_;
}
inline void MetaCacheHead::_internal_set_is_sorted(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_sorted_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // cache_2eproto_2epb_2eh
