edition = "2024";

package proto;

enum Platform {
	YOUTUBE = 0;
	SPOTIFY = 1;
	INVALID = 2;
}

message Song {
	repeated string artists = 1;
	string track = 2;
}

message PlaylistItems {
    message PairSongItems {
        Song song = 1;
        repeated string items = 2;
    }

    string id = 1;
    string etag = 2;
    repeated PairSongItems song_items_pairs = 3;
}

// TODO change to reflect new Playlist layout
message Playlist {
	string id = 1;
	bytes id_hash = 2;
	string title = 3;
    Platform plat = 4;
	bool is_private = 5;
	string etag = 6;
	string version = 7;
	int32 num_items = 8;
	string tracker = 9;
}

message CacheHead {
	bytes next = 1;
	string etag = 2;
}

message CacheNode {
	bytes next = 1;
	bytes prev = 2;
	Playlist playlist = 3;
}

message PlaylistTracker {
    message PairPlatformId {
        Platform plat = 1;
        bytes id_hash = 2;
    }

	repeated PairPlatformId plat_id_hash_pairs = 1;
}

message PlaylistItemIdToSongMap {
	message Entry {
		string playlist_item_id = 1;
		Song song = 2;
	}

	message Bucket {
		repeated Entry entries = 1;
	}

	// map type exists but doing it manually for fun
	repeated Bucket buckets = 1;
}
