// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playlist_cache.proto
// Protobuf C++ Version: 6.33.5

#ifndef playlist_5fcache_2eproto_2epb_2eh
#define playlist_5fcache_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_playlist_5fcache_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_playlist_5fcache_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_playlist_5fcache_2eproto;
}  // extern "C"
namespace proto {
class CacheHead;
struct CacheHeadDefaultTypeInternal;
extern CacheHeadDefaultTypeInternal _CacheHead_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CacheHead_class_data_;
class CacheNode;
struct CacheNodeDefaultTypeInternal;
extern CacheNodeDefaultTypeInternal _CacheNode_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CacheNode_class_data_;
class Playlist;
struct PlaylistDefaultTypeInternal;
extern PlaylistDefaultTypeInternal _Playlist_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Playlist_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class Playlist final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.Playlist) */ {
 public:
  inline Playlist() : Playlist(nullptr) {}
  ~Playlist() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Playlist* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Playlist));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Playlist(::google::protobuf::internal::ConstantInitialized);

  inline Playlist(const Playlist& from) : Playlist(nullptr, from) {}
  inline Playlist(Playlist&& from) noexcept
      : Playlist(nullptr, ::std::move(from)) {}
  inline Playlist& operator=(const Playlist& from) {
    CopyFrom(from);
    return *this;
  }
  inline Playlist& operator=(Playlist&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Playlist& default_instance() {
    return *reinterpret_cast<const Playlist*>(
        &_Playlist_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Playlist& a, Playlist& b) { a.Swap(&b); }
  inline void Swap(Playlist* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Playlist* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Playlist* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Playlist>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Playlist& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Playlist& from) { Playlist::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Playlist* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.Playlist"; }

  explicit Playlist(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Playlist(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Playlist& from);
  Playlist(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Playlist&& from) noexcept
      : Playlist(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kEtagFieldNumber = 2,
    kTitleFieldNumber = 3,
    kShortIdFieldNumber = 6,
    kIsPrivateFieldNumber = 4,
    kItemsFieldNumber = 5,
  };
  // string id = 1;
  bool has_id() const;
  void clear_id() ;
  ::absl::string_view id() const;
  template <typename Arg_ = ::std::string&&>
  void set_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(::absl::string_view value);

  public:
  // string etag = 2;
  bool has_etag() const;
  void clear_etag() ;
  ::absl::string_view etag() const;
  template <typename Arg_ = ::std::string&&>
  void set_etag(Arg_&& arg);

  private:
  ::absl::string_view _internal_etag() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_etag(::absl::string_view value);

  public:
  // string title = 3;
  bool has_title() const;
  void clear_title() ;
  ::absl::string_view title() const;
  template <typename Arg_ = ::std::string&&>
  void set_title(Arg_&& arg);

  private:
  ::absl::string_view _internal_title() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_title(::absl::string_view value);

  public:
  // string short_id = 6;
  bool has_short_id() const;
  void clear_short_id() ;
  ::absl::string_view short_id() const;
  template <typename Arg_ = ::std::string&&>
  void set_short_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_short_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_short_id(::absl::string_view value);

  public:
  // bool is_private = 4;
  bool has_is_private() const;
  void clear_is_private() ;
  bool is_private() const;
  void set_is_private(bool value);

  private:
  bool _internal_is_private() const;
  void _internal_set_is_private(bool value);

  public:
  // int32 items = 5;
  bool has_items() const;
  void clear_items() ;
  ::int32_t items() const;
  void set_items(::int32_t value);

  private:
  ::int32_t _internal_items() const;
  void _internal_set_items(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.Playlist)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Playlist& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr etag_;
    ::google::protobuf::internal::ArenaStringPtr title_;
    ::google::protobuf::internal::ArenaStringPtr short_id_;
    bool is_private_;
    ::int32_t items_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_playlist_5fcache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Playlist_class_data_;
// -------------------------------------------------------------------

class CacheHead final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CacheHead) */ {
 public:
  inline CacheHead() : CacheHead(nullptr) {}
  ~CacheHead() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CacheHead* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CacheHead));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CacheHead(::google::protobuf::internal::ConstantInitialized);

  inline CacheHead(const CacheHead& from) : CacheHead(nullptr, from) {}
  inline CacheHead(CacheHead&& from) noexcept
      : CacheHead(nullptr, ::std::move(from)) {}
  inline CacheHead& operator=(const CacheHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline CacheHead& operator=(CacheHead&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CacheHead& default_instance() {
    return *reinterpret_cast<const CacheHead*>(
        &_CacheHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CacheHead& a, CacheHead& b) { a.Swap(&b); }
  inline void Swap(CacheHead* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CacheHead* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CacheHead* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CacheHead>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CacheHead& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CacheHead& from) { CacheHead::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CacheHead* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CacheHead"; }

  explicit CacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CacheHead& from);
  CacheHead(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CacheHead&& from) noexcept
      : CacheHead(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextFieldNumber = 1,
  };
  // string next = 1;
  bool has_next() const;
  void clear_next() ;
  ::absl::string_view next() const;
  template <typename Arg_ = ::std::string&&>
  void set_next(Arg_&& arg);

  private:
  ::absl::string_view _internal_next() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_next(::absl::string_view value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CacheHead)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CacheHead& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr next_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_playlist_5fcache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CacheHead_class_data_;
// -------------------------------------------------------------------

class CacheNode final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CacheNode) */ {
 public:
  inline CacheNode() : CacheNode(nullptr) {}
  ~CacheNode() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CacheNode* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CacheNode));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CacheNode(::google::protobuf::internal::ConstantInitialized);

  inline CacheNode(const CacheNode& from) : CacheNode(nullptr, from) {}
  inline CacheNode(CacheNode&& from) noexcept
      : CacheNode(nullptr, ::std::move(from)) {}
  inline CacheNode& operator=(const CacheNode& from) {
    CopyFrom(from);
    return *this;
  }
  inline CacheNode& operator=(CacheNode&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CacheNode& default_instance() {
    return *reinterpret_cast<const CacheNode*>(
        &_CacheNode_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CacheNode& a, CacheNode& b) { a.Swap(&b); }
  inline void Swap(CacheNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CacheNode* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CacheNode* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CacheNode>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CacheNode& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CacheNode& from) { CacheNode::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CacheNode* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CacheNode"; }

  explicit CacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CacheNode& from);
  CacheNode(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CacheNode&& from) noexcept
      : CacheNode(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextFieldNumber = 1,
    kPlaylistFieldNumber = 2,
    kIsTrackedFieldNumber = 3,
  };
  // string next = 1;
  bool has_next() const;
  void clear_next() ;
  ::absl::string_view next() const;
  template <typename Arg_ = ::std::string&&>
  void set_next(Arg_&& arg);

  private:
  ::absl::string_view _internal_next() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_next(::absl::string_view value);

  public:
  // .proto.Playlist playlist = 2;
  bool has_playlist() const;
  void clear_playlist() ;
  const ::proto::Playlist& playlist() const;
  [[nodiscard]] ::proto::Playlist* PROTOBUF_NULLABLE release_playlist();
  ::proto::Playlist* PROTOBUF_NONNULL mutable_playlist();
  void set_allocated_playlist(::proto::Playlist* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_playlist(::proto::Playlist* PROTOBUF_NULLABLE value);
  ::proto::Playlist* PROTOBUF_NULLABLE unsafe_arena_release_playlist();

  private:
  const ::proto::Playlist& _internal_playlist() const;
  ::proto::Playlist* PROTOBUF_NONNULL _internal_mutable_playlist();

  public:
  // bool is_tracked = 3;
  bool has_is_tracked() const;
  void clear_is_tracked() ;
  bool is_tracked() const;
  void set_is_tracked(bool value);

  private:
  bool _internal_is_tracked() const;
  void _internal_set_is_tracked(bool value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CacheNode)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 28,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CacheNode& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr next_;
    ::proto::Playlist* PROTOBUF_NULLABLE playlist_;
    bool is_tracked_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_playlist_5fcache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CacheNode_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CacheHead

// string next = 1;
inline bool CacheHead::has_next() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CacheHead::clear_next() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view CacheHead::next() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CacheHead.next)
  return _internal_next();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CacheHead::set_next(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.next_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.CacheHead.next)
}
inline ::absl::string_view CacheHead::_internal_next() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.next_.Get();
}
inline void CacheHead::_internal_set_next(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.next_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// Playlist

// string id = 1;
inline bool Playlist::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Playlist::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view Playlist::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.Playlist.id)
  return _internal_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void Playlist::set_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.Playlist.id)
}
inline ::absl::string_view Playlist::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void Playlist::_internal_set_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(value, GetArena());
}

// string etag = 2;
inline bool Playlist::has_etag() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Playlist::clear_etag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.etag_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view Playlist::etag() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.Playlist.etag)
  return _internal_etag();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void Playlist::set_etag(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.etag_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.Playlist.etag)
}
inline ::absl::string_view Playlist::_internal_etag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.etag_.Get();
}
inline void Playlist::_internal_set_etag(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.etag_.Set(value, GetArena());
}

// string title = 3;
inline bool Playlist::has_title() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Playlist::clear_title() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.title_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::absl::string_view Playlist::title() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.Playlist.title)
  return _internal_title();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void Playlist::set_title(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.title_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.Playlist.title)
}
inline ::absl::string_view Playlist::_internal_title() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.title_.Get();
}
inline void Playlist::_internal_set_title(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.title_.Set(value, GetArena());
}

// bool is_private = 4;
inline bool Playlist::has_is_private() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void Playlist::clear_is_private() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_private_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline bool Playlist::is_private() const {
  // @@protoc_insertion_point(field_get:proto.Playlist.is_private)
  return _internal_is_private();
}
inline void Playlist::set_is_private(bool value) {
  _internal_set_is_private(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:proto.Playlist.is_private)
}
inline bool Playlist::_internal_is_private() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_private_;
}
inline void Playlist::_internal_set_is_private(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_private_ = value;
}

// int32 items = 5;
inline bool Playlist::has_items() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void Playlist::clear_items() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t Playlist::items() const {
  // @@protoc_insertion_point(field_get:proto.Playlist.items)
  return _internal_items();
}
inline void Playlist::set_items(::int32_t value) {
  _internal_set_items(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:proto.Playlist.items)
}
inline ::int32_t Playlist::_internal_items() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_;
}
inline void Playlist::_internal_set_items(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_ = value;
}

// string short_id = 6;
inline bool Playlist::has_short_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void Playlist::clear_short_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.short_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::absl::string_view Playlist::short_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.Playlist.short_id)
  return _internal_short_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void Playlist::set_short_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.short_id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.Playlist.short_id)
}
inline ::absl::string_view Playlist::_internal_short_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.short_id_.Get();
}
inline void Playlist::_internal_set_short_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.short_id_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// CacheNode

// string next = 1;
inline bool CacheNode::has_next() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CacheNode::clear_next() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view CacheNode::next() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CacheNode.next)
  return _internal_next();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void CacheNode::set_next(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.next_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.CacheNode.next)
}
inline ::absl::string_view CacheNode::_internal_next() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.next_.Get();
}
inline void CacheNode::_internal_set_next(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.next_.Set(value, GetArena());
}

// .proto.Playlist playlist = 2;
inline bool CacheNode::has_playlist() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.playlist_ != nullptr);
  return value;
}
inline void CacheNode::clear_playlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playlist_ != nullptr) _impl_.playlist_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::proto::Playlist& CacheNode::_internal_playlist() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::proto::Playlist* p = _impl_.playlist_;
  return p != nullptr ? *p : reinterpret_cast<const ::proto::Playlist&>(::proto::_Playlist_default_instance_);
}
inline const ::proto::Playlist& CacheNode::playlist() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CacheNode.playlist)
  return _internal_playlist();
}
inline void CacheNode::unsafe_arena_set_allocated_playlist(
    ::proto::Playlist* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.playlist_);
  }
  _impl_.playlist_ = reinterpret_cast<::proto::Playlist*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:proto.CacheNode.playlist)
}
inline ::proto::Playlist* PROTOBUF_NULLABLE CacheNode::release_playlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::Playlist* released = _impl_.playlist_;
  _impl_.playlist_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::proto::Playlist* PROTOBUF_NULLABLE CacheNode::unsafe_arena_release_playlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CacheNode.playlist)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::Playlist* temp = _impl_.playlist_;
  _impl_.playlist_ = nullptr;
  return temp;
}
inline ::proto::Playlist* PROTOBUF_NONNULL CacheNode::_internal_mutable_playlist() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.playlist_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::proto::Playlist>(GetArena());
    _impl_.playlist_ = reinterpret_cast<::proto::Playlist*>(p);
  }
  return _impl_.playlist_;
}
inline ::proto::Playlist* PROTOBUF_NONNULL CacheNode::mutable_playlist()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::proto::Playlist* _msg = _internal_mutable_playlist();
  // @@protoc_insertion_point(field_mutable:proto.CacheNode.playlist)
  return _msg;
}
inline void CacheNode::set_allocated_playlist(::proto::Playlist* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.playlist_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.playlist_ = reinterpret_cast<::proto::Playlist*>(value);
  // @@protoc_insertion_point(field_set_allocated:proto.CacheNode.playlist)
}

// bool is_tracked = 3;
inline bool CacheNode::has_is_tracked() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CacheNode::clear_is_tracked() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_tracked_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool CacheNode::is_tracked() const {
  // @@protoc_insertion_point(field_get:proto.CacheNode.is_tracked)
  return _internal_is_tracked();
}
inline void CacheNode::set_is_tracked(bool value) {
  _internal_set_is_tracked(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.CacheNode.is_tracked)
}
inline bool CacheNode::_internal_is_tracked() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_tracked_;
}
inline void CacheNode::_internal_set_is_tracked(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_tracked_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // playlist_5fcache_2eproto_2epb_2eh
