// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playlist_items_cache.proto
// Protobuf C++ Version: 6.33.5

#ifndef playlist_5fitems_5fcache_2eproto_2epb_2eh
#define playlist_5fitems_5fcache_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_playlist_5fitems_5fcache_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_playlist_5fitems_5fcache_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_playlist_5fitems_5fcache_2eproto;
}  // extern "C"
namespace proto {
enum Platform : int;
extern const uint32_t Platform_internal_data_[];
class PlaylistInfo;
struct PlaylistInfoDefaultTypeInternal;
extern PlaylistInfoDefaultTypeInternal _PlaylistInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlaylistInfo_class_data_;
class PlaylistItems;
struct PlaylistItemsDefaultTypeInternal;
extern PlaylistItemsDefaultTypeInternal _PlaylistItems_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PlaylistItems_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::proto::Platform_internal_data_>
    internal::EnumTraitsImpl::value<::proto::Platform>;
}  // namespace protobuf
}  // namespace google

namespace proto {
enum Platform : int {
  YOUTUBE = 0,
  SPOTIFY = 1,
  INVALID = 2,
  Platform_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Platform_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Platform_internal_data_[];
inline constexpr Platform Platform_MIN =
    static_cast<Platform>(0);
inline constexpr Platform Platform_MAX =
    static_cast<Platform>(2);
inline bool Platform_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Platform_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Platform_descriptor();
template <typename T>
::absl::string_view Platform_Name(T value) {
  static_assert(::std::is_same<T, Platform>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Platform_Name().");
  return Platform_Name(static_cast<Platform>(value));
}
template <>
inline ::absl::string_view Platform_Name(Platform value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Platform_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Platform_Parse(
    ::absl::string_view name, Platform* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Platform>(Platform_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class PlaylistInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.PlaylistInfo) */ {
 public:
  inline PlaylistInfo() : PlaylistInfo(nullptr) {}
  ~PlaylistInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlaylistInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlaylistInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlaylistInfo(::google::protobuf::internal::ConstantInitialized);

  inline PlaylistInfo(const PlaylistInfo& from) : PlaylistInfo(nullptr, from) {}
  inline PlaylistInfo(PlaylistInfo&& from) noexcept
      : PlaylistInfo(nullptr, ::std::move(from)) {}
  inline PlaylistInfo& operator=(const PlaylistInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlaylistInfo& operator=(PlaylistInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlaylistInfo& default_instance() {
    return *reinterpret_cast<const PlaylistInfo*>(
        &_PlaylistInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PlaylistInfo& a, PlaylistInfo& b) { a.Swap(&b); }
  inline void Swap(PlaylistInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlaylistInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlaylistInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlaylistInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlaylistInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlaylistInfo& from) { PlaylistInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlaylistInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.PlaylistInfo"; }

  explicit PlaylistInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlaylistInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlaylistInfo& from);
  PlaylistInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlaylistInfo&& from) noexcept
      : PlaylistInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 2,
    kItemsEtagFieldNumber = 3,
    kPlatFieldNumber = 1,
  };
  // string id = 2;
  bool has_id() const;
  void clear_id() ;
  ::absl::string_view id() const;
  template <typename Arg_ = ::std::string&&>
  void set_id(Arg_&& arg);

  private:
  ::absl::string_view _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(::absl::string_view value);

  public:
  // string items_etag = 3;
  bool has_items_etag() const;
  void clear_items_etag() ;
  ::absl::string_view items_etag() const;
  template <typename Arg_ = ::std::string&&>
  void set_items_etag(Arg_&& arg);

  private:
  ::absl::string_view _internal_items_etag() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_items_etag(::absl::string_view value);

  public:
  // .proto.Platform plat = 1;
  bool has_plat() const;
  void clear_plat() ;
  ::proto::Platform plat() const;
  void set_plat(::proto::Platform value);

  private:
  ::proto::Platform _internal_plat() const;
  void _internal_set_plat(::proto::Platform value);

  public:
  // @@protoc_insertion_point(class_scope:proto.PlaylistInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlaylistInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr items_etag_;
    int plat_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_playlist_5fitems_5fcache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlaylistInfo_class_data_;
// -------------------------------------------------------------------

class PlaylistItems final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.PlaylistItems) */ {
 public:
  inline PlaylistItems() : PlaylistItems(nullptr) {}
  ~PlaylistItems() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlaylistItems* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlaylistItems));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlaylistItems(::google::protobuf::internal::ConstantInitialized);

  inline PlaylistItems(const PlaylistItems& from) : PlaylistItems(nullptr, from) {}
  inline PlaylistItems(PlaylistItems&& from) noexcept
      : PlaylistItems(nullptr, ::std::move(from)) {}
  inline PlaylistItems& operator=(const PlaylistItems& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlaylistItems& operator=(PlaylistItems&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlaylistItems& default_instance() {
    return *reinterpret_cast<const PlaylistItems*>(
        &_PlaylistItems_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PlaylistItems& a, PlaylistItems& b) { a.Swap(&b); }
  inline void Swap(PlaylistItems* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlaylistItems* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlaylistItems* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlaylistItems>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlaylistItems& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlaylistItems& from) { PlaylistItems::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlaylistItems* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.PlaylistItems"; }

  explicit PlaylistItems(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PlaylistItems(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlaylistItems& from);
  PlaylistItems(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PlaylistItems&& from) noexcept
      : PlaylistItems(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTrackedPlaylistsFieldNumber = 1,
    kSongHashesFieldNumber = 2,
  };
  // repeated .proto.PlaylistInfo tracked_playlists = 1;
  int tracked_playlists_size() const;
  private:
  int _internal_tracked_playlists_size() const;

  public:
  void clear_tracked_playlists() ;
  ::proto::PlaylistInfo* PROTOBUF_NONNULL mutable_tracked_playlists(int index);
  ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>* PROTOBUF_NONNULL mutable_tracked_playlists();

  private:
  const ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>& _internal_tracked_playlists() const;
  ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>* PROTOBUF_NONNULL _internal_mutable_tracked_playlists();
  public:
  const ::proto::PlaylistInfo& tracked_playlists(int index) const;
  ::proto::PlaylistInfo* PROTOBUF_NONNULL add_tracked_playlists();
  const ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>& tracked_playlists() const;
  // repeated bytes song_hashes = 2;
  int song_hashes_size() const;
  private:
  int _internal_song_hashes_size() const;

  public:
  void clear_song_hashes() ;
  ::absl::string_view song_hashes(int index) const;
  template <typename Arg_ = ::std::string&&>
  void set_song_hashes(int index, Arg_&& value);
  template <typename Arg_ = ::std::string&&>
  void add_song_hashes(Arg_&& value);
  const ::google::protobuf::RepeatedPtrField<::std::string>& song_hashes() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_song_hashes();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_song_hashes() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_song_hashes();

  public:
  // @@protoc_insertion_point(class_scope:proto.PlaylistItems)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PlaylistItems& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::proto::PlaylistInfo > tracked_playlists_;
    ::google::protobuf::RepeatedPtrField<::std::string> song_hashes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_playlist_5fitems_5fcache_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PlaylistItems_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlaylistInfo

// .proto.Platform plat = 1;
inline bool PlaylistInfo::has_plat() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void PlaylistInfo::clear_plat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.plat_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::proto::Platform PlaylistInfo::plat() const {
  // @@protoc_insertion_point(field_get:proto.PlaylistInfo.plat)
  return _internal_plat();
}
inline void PlaylistInfo::set_plat(::proto::Platform value) {
  _internal_set_plat(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.PlaylistInfo.plat)
}
inline ::proto::Platform PlaylistInfo::_internal_plat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::proto::Platform>(_impl_.plat_);
}
inline void PlaylistInfo::_internal_set_plat(::proto::Platform value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.plat_ = value;
}

// string id = 2;
inline bool PlaylistInfo::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void PlaylistInfo::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::absl::string_view PlaylistInfo::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.PlaylistInfo.id)
  return _internal_id();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistInfo::set_id(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.PlaylistInfo.id)
}
inline ::absl::string_view PlaylistInfo::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void PlaylistInfo::_internal_set_id(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(value, GetArena());
}

// string items_etag = 3;
inline bool PlaylistInfo::has_items_etag() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void PlaylistInfo::clear_items_etag() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.items_etag_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view PlaylistInfo::items_etag() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.PlaylistInfo.items_etag)
  return _internal_items_etag();
}
template <typename Arg_>
PROTOBUF_ALWAYS_INLINE void PlaylistInfo::set_items_etag(Arg_&& arg) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.items_etag_.Set(static_cast<Arg_&&>(arg), GetArena());
  // @@protoc_insertion_point(field_set:proto.PlaylistInfo.items_etag)
}
inline ::absl::string_view PlaylistInfo::_internal_items_etag() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.items_etag_.Get();
}
inline void PlaylistInfo::_internal_set_items_etag(::absl::string_view value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.items_etag_.Set(value, GetArena());
}

// -------------------------------------------------------------------

// PlaylistItems

// repeated .proto.PlaylistInfo tracked_playlists = 1;
inline int PlaylistItems::_internal_tracked_playlists_size() const {
  return _internal_tracked_playlists().size();
}
inline int PlaylistItems::tracked_playlists_size() const {
  return _internal_tracked_playlists_size();
}
inline void PlaylistItems::clear_tracked_playlists() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tracked_playlists_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::proto::PlaylistInfo* PROTOBUF_NONNULL PlaylistItems::mutable_tracked_playlists(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:proto.PlaylistItems.tracked_playlists)
  return _internal_mutable_tracked_playlists()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>* PROTOBUF_NONNULL PlaylistItems::mutable_tracked_playlists()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:proto.PlaylistItems.tracked_playlists)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tracked_playlists();
}
inline const ::proto::PlaylistInfo& PlaylistItems::tracked_playlists(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.PlaylistItems.tracked_playlists)
  return _internal_tracked_playlists().Get(index);
}
inline ::proto::PlaylistInfo* PROTOBUF_NONNULL PlaylistItems::add_tracked_playlists()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::proto::PlaylistInfo* _add =
      _internal_mutable_tracked_playlists()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:proto.PlaylistItems.tracked_playlists)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>& PlaylistItems::tracked_playlists() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.PlaylistItems.tracked_playlists)
  return _internal_tracked_playlists();
}
inline const ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>&
PlaylistItems::_internal_tracked_playlists() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tracked_playlists_;
}
inline ::google::protobuf::RepeatedPtrField<::proto::PlaylistInfo>* PROTOBUF_NONNULL
PlaylistItems::_internal_mutable_tracked_playlists() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tracked_playlists_;
}

// repeated bytes song_hashes = 2;
inline int PlaylistItems::_internal_song_hashes_size() const {
  return _internal_song_hashes().size();
}
inline int PlaylistItems::song_hashes_size() const {
  return _internal_song_hashes_size();
}
inline void PlaylistItems::clear_song_hashes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.song_hashes_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::absl::string_view PlaylistItems::song_hashes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.PlaylistItems.song_hashes)
  return _internal_song_hashes().Get(index);
}
template <typename Arg_>
inline void PlaylistItems::set_song_hashes(int index, Arg_&& value) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_song_hashes()->Mutable(index), ::std::forward<Arg_>(value) , ::google::protobuf::internal::BytesTag{});
  // @@protoc_insertion_point(field_set:proto.PlaylistItems.song_hashes)
}
template <typename Arg_>
inline void PlaylistItems::add_song_hashes(Arg_&& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(::google::protobuf::MessageLite::internal_visibility(),
                               GetArena(),
                               *_internal_mutable_song_hashes(),
                               ::std::forward<Arg_>(value) , ::google::protobuf::internal::BytesTag{});
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:proto.PlaylistItems.song_hashes)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& PlaylistItems::song_hashes()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:proto.PlaylistItems.song_hashes)
  return _internal_song_hashes();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
PlaylistItems::mutable_song_hashes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:proto.PlaylistItems.song_hashes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_song_hashes();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
PlaylistItems::_internal_song_hashes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.song_hashes_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
PlaylistItems::_internal_mutable_song_hashes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.song_hashes_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::proto::Platform> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::proto::Platform>() {
  return ::proto::Platform_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // playlist_5fitems_5fcache_2eproto_2epb_2eh
