// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cache.proto
// Protobuf C++ Version: 6.33.5

#include "../include/cache.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr PlaylistCacheHead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        is_sorted_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistCacheHead::PlaylistCacheHead(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistCacheHead_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistCacheHeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistCacheHeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistCacheHeadDefaultTypeInternal() {}
  union {
    PlaylistCacheHead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistCacheHeadDefaultTypeInternal _PlaylistCacheHead_default_instance_;

inline constexpr PlaylistCacheEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        etag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_private_{false},
        items_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistCacheEntry::PlaylistCacheEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistCacheEntry_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistCacheEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistCacheEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistCacheEntryDefaultTypeInternal() {}
  union {
    PlaylistCacheEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistCacheEntryDefaultTypeInternal _PlaylistCacheEntry_default_instance_;

inline constexpr PlaylistCacheNode::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        next_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        entry_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistCacheNode::PlaylistCacheNode(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistCacheNode_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistCacheNodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistCacheNodeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistCacheNodeDefaultTypeInternal() {}
  union {
    PlaylistCacheNode _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistCacheNodeDefaultTypeInternal _PlaylistCacheNode_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_cache_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_cache_2eproto = nullptr;
const ::uint32_t
    TableStruct_cache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_.etag_),
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_.is_private_),
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheEntry, _impl_.id_hash_),
        0,
        1,
        2,
        4,
        5,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheNode, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheNode, _impl_.entry_),
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheNode, _impl_.next_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheHead, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::PlaylistCacheHead, _impl_.is_sorted_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::PlaylistCacheEntry)},
        {15, sizeof(::PlaylistCacheNode)},
        {22, sizeof(::PlaylistCacheHead)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_PlaylistCacheEntry_default_instance_._instance,
    &::_PlaylistCacheNode_default_instance_._instance,
    &::_PlaylistCacheHead_default_instance_._instance,
};
const char descriptor_table_protodef_cache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013cache.proto\"q\n\022PlaylistCacheEntry\022\n\n\002i"
    "d\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\022\n\n"
    "is_private\030\004 \001(\010\022\r\n\005items\030\005 \001(\005\022\017\n\007id_ha"
    "sh\030\006 \001(\014\"E\n\021PlaylistCacheNode\022\"\n\005entry\030\001"
    " \001(\0132\023.PlaylistCacheEntry\022\014\n\004next\030\002 \001(\t\""
    "&\n\021PlaylistCacheHead\022\021\n\tis_sorted\030d \001(\010b"
    "\010editionsp\351\007"
};
static ::absl::once_flag descriptor_table_cache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cache_2eproto = {
    false,
    false,
    252,
    descriptor_table_protodef_cache_2eproto,
    "cache.proto",
    &descriptor_table_cache_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_cache_2eproto::offsets,
    file_level_enum_descriptors_cache_2eproto,
    file_level_service_descriptors_cache_2eproto,
};
// ===================================================================

class PlaylistCacheEntry::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistCacheEntry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_._has_bits_);
};

PlaylistCacheEntry::PlaylistCacheEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistCacheEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PlaylistCacheEntry)
}
PROTOBUF_NDEBUG_INLINE PlaylistCacheEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PlaylistCacheEntry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        etag_(arena, from.etag_),
        title_(arena, from.title_),
        id_hash_(arena, from.id_hash_) {}

PlaylistCacheEntry::PlaylistCacheEntry(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaylistCacheEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistCacheEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaylistCacheEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_private_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, is_private_),
           offsetof(Impl_, items_) -
               offsetof(Impl_, is_private_) +
               sizeof(Impl_::items_));

  // @@protoc_insertion_point(copy_constructor:PlaylistCacheEntry)
}
PROTOBUF_NDEBUG_INLINE PlaylistCacheEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        etag_(arena),
        title_(arena),
        id_hash_(arena) {}

inline void PlaylistCacheEntry::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_private_),
           0,
           offsetof(Impl_, items_) -
               offsetof(Impl_, is_private_) +
               sizeof(Impl_::items_));
}
PlaylistCacheEntry::~PlaylistCacheEntry() {
  // @@protoc_insertion_point(destructor:PlaylistCacheEntry)
  SharedDtor(*this);
}
inline void PlaylistCacheEntry::SharedDtor(MessageLite& self) {
  PlaylistCacheEntry& this_ = static_cast<PlaylistCacheEntry&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.etag_.Destroy();
  this_._impl_.title_.Destroy();
  this_._impl_.id_hash_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistCacheEntry::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistCacheEntry(arena);
}
constexpr auto PlaylistCacheEntry::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PlaylistCacheEntry),
                                            alignof(PlaylistCacheEntry));
}
constexpr auto PlaylistCacheEntry::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistCacheEntry_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistCacheEntry::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistCacheEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistCacheEntry::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistCacheEntry>(), &PlaylistCacheEntry::ByteSizeLong,
              &PlaylistCacheEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_._cached_size_),
          false,
      },
      &PlaylistCacheEntry::kDescriptorMethods,
      &descriptor_table_cache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistCacheEntry_class_data_ =
        PlaylistCacheEntry::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistCacheEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistCacheEntry_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistCacheEntry_class_data_.tc_table);
  return PlaylistCacheEntry_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 38, 2>
PlaylistCacheEntry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlaylistCacheEntry_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PlaylistCacheEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.id_)}},
    // string etag = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.etag_)}},
    // string title = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.title_)}},
    // bool is_private = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PlaylistCacheEntry, _impl_.is_private_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.is_private_)}},
    // int32 items = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlaylistCacheEntry, _impl_.items_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.items_)}},
    // bytes id_hash = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 3, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.id_hash_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string etag = 2;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.etag_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string title = 3;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.title_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_private = 4;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.is_private_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // int32 items = 5;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.items_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bytes id_hash = 6;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.id_hash_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\2\4\5\0\0\0\0"
    "PlaylistCacheEntry"
    "id"
    "etag"
    "title"
  }},
};
PROTOBUF_NOINLINE void PlaylistCacheEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:PlaylistCacheEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.etag_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.id_hash_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000030U)) {
    ::memset(&_impl_.is_private_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.items_) -
        reinterpret_cast<char*>(&_impl_.is_private_)) + sizeof(_impl_.items_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistCacheEntry::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistCacheEntry& this_ = static_cast<const PlaylistCacheEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistCacheEntry::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistCacheEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PlaylistCacheEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PlaylistCacheEntry.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string etag = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_etag();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PlaylistCacheEntry.etag");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string title = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::absl::string_view _s = this_._internal_title();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PlaylistCacheEntry.title");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bool is_private = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_is_private(), target);
  }

  // int32 items = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_items(), target);
  }

  // bytes id_hash = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::absl::string_view _s = this_._internal_id_hash();
    target = stream->WriteBytesMaybeAliased(6, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlaylistCacheEntry)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistCacheEntry::ByteSizeLong(const MessageLite& base) {
  const PlaylistCacheEntry& this_ = static_cast<const PlaylistCacheEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistCacheEntry::ByteSizeLong() const {
  const PlaylistCacheEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PlaylistCacheEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000010U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x0000002fU)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
    // string etag = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_etag());
    }
    // string title = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_title());
    }
    // bytes id_hash = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_id_hash());
    }
    // int32 items = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_items());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistCacheEntry::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistCacheEntry*>(&to_msg);
  auto& from = static_cast<const PlaylistCacheEntry&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:PlaylistCacheEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_id(from._internal_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_etag(from._internal_etag());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_title(from._internal_title());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_id_hash(from._internal_id_hash());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.is_private_ = from._impl_.is_private_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.items_ = from._impl_.items_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistCacheEntry::CopyFrom(const PlaylistCacheEntry& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PlaylistCacheEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistCacheEntry::InternalSwap(PlaylistCacheEntry* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.id_.InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  _impl_.etag_.InternalSwap(&_impl_.etag_, &other->_impl_.etag_, arena);
  _impl_.title_.InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  _impl_.id_hash_.InternalSwap(&_impl_.id_hash_, &other->_impl_.id_hash_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.items_)
      + sizeof(PlaylistCacheEntry::_impl_.items_)
      - PROTOBUF_FIELD_OFFSET(PlaylistCacheEntry, _impl_.is_private_)>(
          reinterpret_cast<char*>(&_impl_.is_private_),
          reinterpret_cast<char*>(&other->_impl_.is_private_));
}

::google::protobuf::Metadata PlaylistCacheEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlaylistCacheNode::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistCacheNode>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_._has_bits_);
};

PlaylistCacheNode::PlaylistCacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistCacheNode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PlaylistCacheNode)
}
PROTOBUF_NDEBUG_INLINE PlaylistCacheNode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::PlaylistCacheNode& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        next_(arena, from.next_) {}

PlaylistCacheNode::PlaylistCacheNode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaylistCacheNode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistCacheNode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaylistCacheNode* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.entry_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.entry_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:PlaylistCacheNode)
}
PROTOBUF_NDEBUG_INLINE PlaylistCacheNode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        next_(arena) {}

inline void PlaylistCacheNode::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.entry_ = {};
}
PlaylistCacheNode::~PlaylistCacheNode() {
  // @@protoc_insertion_point(destructor:PlaylistCacheNode)
  SharedDtor(*this);
}
inline void PlaylistCacheNode::SharedDtor(MessageLite& self) {
  PlaylistCacheNode& this_ = static_cast<PlaylistCacheNode&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.next_.Destroy();
  delete this_._impl_.entry_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistCacheNode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistCacheNode(arena);
}
constexpr auto PlaylistCacheNode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PlaylistCacheNode),
                                            alignof(PlaylistCacheNode));
}
constexpr auto PlaylistCacheNode::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistCacheNode_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistCacheNode::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistCacheNode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistCacheNode::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistCacheNode>(), &PlaylistCacheNode::ByteSizeLong,
              &PlaylistCacheNode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_._cached_size_),
          false,
      },
      &PlaylistCacheNode::kDescriptorMethods,
      &descriptor_table_cache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistCacheNode_class_data_ =
        PlaylistCacheNode::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistCacheNode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistCacheNode_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistCacheNode_class_data_.tc_table);
  return PlaylistCacheNode_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 30, 2>
PlaylistCacheNode::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PlaylistCacheNode_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PlaylistCacheNode>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string next = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_.next_)}},
    // .PlaylistCacheEntry entry = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_.entry_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .PlaylistCacheEntry entry = 1;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_.entry_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string next = 2;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheNode, _impl_.next_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::PlaylistCacheEntry>()},
  }},
  {{
    "\21\0\4\0\0\0\0\0"
    "PlaylistCacheNode"
    "next"
  }},
};
PROTOBUF_NOINLINE void PlaylistCacheNode::Clear() {
// @@protoc_insertion_point(message_clear_start:PlaylistCacheNode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.next_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.entry_ != nullptr);
      _impl_.entry_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistCacheNode::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistCacheNode& this_ = static_cast<const PlaylistCacheNode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistCacheNode::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistCacheNode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PlaylistCacheNode)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .PlaylistCacheEntry entry = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.entry_, this_._impl_.entry_->GetCachedSize(), target,
        stream);
  }

  // string next = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_next();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "PlaylistCacheNode.next");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlaylistCacheNode)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistCacheNode::ByteSizeLong(const MessageLite& base) {
  const PlaylistCacheNode& this_ = static_cast<const PlaylistCacheNode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistCacheNode::ByteSizeLong() const {
  const PlaylistCacheNode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PlaylistCacheNode)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string next = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_next());
    }
    // .PlaylistCacheEntry entry = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.entry_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistCacheNode::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistCacheNode*>(&to_msg);
  auto& from = static_cast<const PlaylistCacheNode&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:PlaylistCacheNode)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_next(from._internal_next());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.entry_ != nullptr);
      if (_this->_impl_.entry_ == nullptr) {
        _this->_impl_.entry_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.entry_);
      } else {
        _this->_impl_.entry_->MergeFrom(*from._impl_.entry_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistCacheNode::CopyFrom(const PlaylistCacheNode& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PlaylistCacheNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistCacheNode::InternalSwap(PlaylistCacheNode* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.next_.InternalSwap(&_impl_.next_, &other->_impl_.next_, arena);
  swap(_impl_.entry_, other->_impl_.entry_);
}

::google::protobuf::Metadata PlaylistCacheNode::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlaylistCacheHead::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistCacheHead>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistCacheHead, _impl_._has_bits_);
};

PlaylistCacheHead::PlaylistCacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistCacheHead_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:PlaylistCacheHead)
}
PlaylistCacheHead::PlaylistCacheHead(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PlaylistCacheHead& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistCacheHead_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PlaylistCacheHead::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PlaylistCacheHead::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_sorted_ = {};
}
PlaylistCacheHead::~PlaylistCacheHead() {
  // @@protoc_insertion_point(destructor:PlaylistCacheHead)
  SharedDtor(*this);
}
inline void PlaylistCacheHead::SharedDtor(MessageLite& self) {
  PlaylistCacheHead& this_ = static_cast<PlaylistCacheHead&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistCacheHead::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistCacheHead(arena);
}
constexpr auto PlaylistCacheHead::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PlaylistCacheHead),
                                            alignof(PlaylistCacheHead));
}
constexpr auto PlaylistCacheHead::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistCacheHead_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistCacheHead::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistCacheHead>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistCacheHead::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistCacheHead>(), &PlaylistCacheHead::ByteSizeLong,
              &PlaylistCacheHead::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistCacheHead, _impl_._cached_size_),
          false,
      },
      &PlaylistCacheHead::kDescriptorMethods,
      &descriptor_table_cache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistCacheHead_class_data_ =
        PlaylistCacheHead::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistCacheHead::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistCacheHead_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistCacheHead_class_data_.tc_table);
  return PlaylistCacheHead_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 7>
PlaylistCacheHead::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistCacheHead, _impl_._has_bits_),
    0, // no _extensions_
    100, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlaylistCacheHead_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::PlaylistCacheHead>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool is_sorted = 100;
    {::_pbi::TcParser::FastV8S2,
     {1696, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistCacheHead, _impl_.is_sorted_)}},
  }}, {{
    100, 0, 1,
    65534, 0,
    65535, 65535
  }}, {{
    // bool is_sorted = 100;
    {PROTOBUF_FIELD_OFFSET(PlaylistCacheHead, _impl_.is_sorted_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PlaylistCacheHead::Clear() {
// @@protoc_insertion_point(message_clear_start:PlaylistCacheHead)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.is_sorted_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistCacheHead::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistCacheHead& this_ = static_cast<const PlaylistCacheHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistCacheHead::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistCacheHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:PlaylistCacheHead)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool is_sorted = 100;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        100, this_._internal_is_sorted(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PlaylistCacheHead)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistCacheHead::ByteSizeLong(const MessageLite& base) {
  const PlaylistCacheHead& this_ = static_cast<const PlaylistCacheHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistCacheHead::ByteSizeLong() const {
  const PlaylistCacheHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:PlaylistCacheHead)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000001U & cached_has_bits) * 3;
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistCacheHead::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistCacheHead*>(&to_msg);
  auto& from = static_cast<const PlaylistCacheHead&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:PlaylistCacheHead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.is_sorted_ = from._impl_.is_sorted_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistCacheHead::CopyFrom(const PlaylistCacheHead& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:PlaylistCacheHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistCacheHead::InternalSwap(PlaylistCacheHead* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.is_sorted_, other->_impl_.is_sorted_);
}

::google::protobuf::Metadata PlaylistCacheHead::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cache_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
