// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: cache.proto
// Protobuf C++ Version: 6.33.5

#include "../include/cache.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MetaCacheEntry::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        etag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_private_{false},
        items_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MetaCacheEntry::MetaCacheEntry(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MetaCacheEntry_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MetaCacheEntryDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetaCacheEntryDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetaCacheEntryDefaultTypeInternal() {}
  union {
    MetaCacheEntry _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetaCacheEntryDefaultTypeInternal _MetaCacheEntry_default_instance_;

inline constexpr MetaCacheNode::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        prev_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        next_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        entry_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR MetaCacheNode::MetaCacheNode(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MetaCacheNode_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MetaCacheNodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MetaCacheNodeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MetaCacheNodeDefaultTypeInternal() {}
  union {
    MetaCacheNode _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MetaCacheNodeDefaultTypeInternal _MetaCacheNode_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_cache_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_cache_2eproto = nullptr;
const ::uint32_t
    TableStruct_cache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_.etag_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_.is_private_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheEntry, _impl_.id_hash_),
        0,
        1,
        2,
        4,
        5,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::MetaCacheNode, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::MetaCacheNode, _impl_.entry_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheNode, _impl_.prev_),
        PROTOBUF_FIELD_OFFSET(::MetaCacheNode, _impl_.next_),
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::MetaCacheEntry)},
        {15, sizeof(::MetaCacheNode)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_MetaCacheEntry_default_instance_._instance,
    &::_MetaCacheNode_default_instance_._instance,
};
const char descriptor_table_protodef_cache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013cache.proto\"m\n\016MetaCacheEntry\022\n\n\002id\030\001 "
    "\001(\t\022\014\n\004etag\030\002 \001(\t\022\r\n\005title\030\003 \001(\t\022\022\n\nis_p"
    "rivate\030\004 \001(\010\022\r\n\005items\030\005 \001(\005\022\017\n\007id_hash\030\006"
    " \001(\014\"K\n\rMetaCacheNode\022\036\n\005entry\030\001 \001(\0132\017.M"
    "etaCacheEntry\022\014\n\004prev\030\002 \001(\t\022\014\n\004next\030\003 \001("
    "\tb\010editionsp\351\007"
};
static ::absl::once_flag descriptor_table_cache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_cache_2eproto = {
    false,
    false,
    214,
    descriptor_table_protodef_cache_2eproto,
    "cache.proto",
    &descriptor_table_cache_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_cache_2eproto::offsets,
    file_level_enum_descriptors_cache_2eproto,
    file_level_service_descriptors_cache_2eproto,
};
// ===================================================================

class MetaCacheEntry::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MetaCacheEntry>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_._has_bits_);
};

MetaCacheEntry::MetaCacheEntry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MetaCacheEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MetaCacheEntry)
}
PROTOBUF_NDEBUG_INLINE MetaCacheEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::MetaCacheEntry& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        etag_(arena, from.etag_),
        title_(arena, from.title_),
        id_hash_(arena, from.id_hash_) {}

MetaCacheEntry::MetaCacheEntry(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MetaCacheEntry& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MetaCacheEntry_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MetaCacheEntry* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_private_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, is_private_),
           offsetof(Impl_, items_) -
               offsetof(Impl_, is_private_) +
               sizeof(Impl_::items_));

  // @@protoc_insertion_point(copy_constructor:MetaCacheEntry)
}
PROTOBUF_NDEBUG_INLINE MetaCacheEntry::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        etag_(arena),
        title_(arena),
        id_hash_(arena) {}

inline void MetaCacheEntry::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_private_),
           0,
           offsetof(Impl_, items_) -
               offsetof(Impl_, is_private_) +
               sizeof(Impl_::items_));
}
MetaCacheEntry::~MetaCacheEntry() {
  // @@protoc_insertion_point(destructor:MetaCacheEntry)
  SharedDtor(*this);
}
inline void MetaCacheEntry::SharedDtor(MessageLite& self) {
  MetaCacheEntry& this_ = static_cast<MetaCacheEntry&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.etag_.Destroy();
  this_._impl_.title_.Destroy();
  this_._impl_.id_hash_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MetaCacheEntry::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MetaCacheEntry(arena);
}
constexpr auto MetaCacheEntry::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MetaCacheEntry),
                                            alignof(MetaCacheEntry));
}
constexpr auto MetaCacheEntry::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MetaCacheEntry_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MetaCacheEntry::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MetaCacheEntry>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MetaCacheEntry::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MetaCacheEntry>(), &MetaCacheEntry::ByteSizeLong,
              &MetaCacheEntry::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_._cached_size_),
          false,
      },
      &MetaCacheEntry::kDescriptorMethods,
      &descriptor_table_cache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MetaCacheEntry_class_data_ =
        MetaCacheEntry::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MetaCacheEntry::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MetaCacheEntry_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MetaCacheEntry_class_data_.tc_table);
  return MetaCacheEntry_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 34, 2>
MetaCacheEntry::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MetaCacheEntry_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MetaCacheEntry>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.id_)}},
    // string etag = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.etag_)}},
    // string title = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.title_)}},
    // bool is_private = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MetaCacheEntry, _impl_.is_private_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.is_private_)}},
    // int32 items = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MetaCacheEntry, _impl_.items_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.items_)}},
    // bytes id_hash = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 3, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.id_hash_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string etag = 2;
    {PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.etag_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string title = 3;
    {PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.title_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_private = 4;
    {PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.is_private_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // int32 items = 5;
    {PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.items_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bytes id_hash = 6;
    {PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.id_hash_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\2\4\5\0\0\0\0"
    "MetaCacheEntry"
    "id"
    "etag"
    "title"
  }},
};
PROTOBUF_NOINLINE void MetaCacheEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:MetaCacheEntry)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.etag_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.id_hash_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000030U)) {
    ::memset(&_impl_.is_private_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.items_) -
        reinterpret_cast<char*>(&_impl_.is_private_)) + sizeof(_impl_.items_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MetaCacheEntry::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MetaCacheEntry& this_ = static_cast<const MetaCacheEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MetaCacheEntry::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MetaCacheEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:MetaCacheEntry)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MetaCacheEntry.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string etag = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_etag();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MetaCacheEntry.etag");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string title = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::absl::string_view _s = this_._internal_title();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MetaCacheEntry.title");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bool is_private = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_is_private(), target);
  }

  // int32 items = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_items(), target);
  }

  // bytes id_hash = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::absl::string_view _s = this_._internal_id_hash();
    target = stream->WriteBytesMaybeAliased(6, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetaCacheEntry)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MetaCacheEntry::ByteSizeLong(const MessageLite& base) {
  const MetaCacheEntry& this_ = static_cast<const MetaCacheEntry&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MetaCacheEntry::ByteSizeLong() const {
  const MetaCacheEntry& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:MetaCacheEntry)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000010U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x0000002fU)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
    // string etag = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_etag());
    }
    // string title = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_title());
    }
    // bytes id_hash = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_id_hash());
    }
    // int32 items = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_items());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MetaCacheEntry::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MetaCacheEntry*>(&to_msg);
  auto& from = static_cast<const MetaCacheEntry&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:MetaCacheEntry)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_id(from._internal_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_etag(from._internal_etag());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_title(from._internal_title());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_id_hash(from._internal_id_hash());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.is_private_ = from._impl_.is_private_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.items_ = from._impl_.items_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MetaCacheEntry::CopyFrom(const MetaCacheEntry& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:MetaCacheEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MetaCacheEntry::InternalSwap(MetaCacheEntry* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.id_.InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  _impl_.etag_.InternalSwap(&_impl_.etag_, &other->_impl_.etag_, arena);
  _impl_.title_.InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  _impl_.id_hash_.InternalSwap(&_impl_.id_hash_, &other->_impl_.id_hash_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.items_)
      + sizeof(MetaCacheEntry::_impl_.items_)
      - PROTOBUF_FIELD_OFFSET(MetaCacheEntry, _impl_.is_private_)>(
          reinterpret_cast<char*>(&_impl_.is_private_),
          reinterpret_cast<char*>(&other->_impl_.is_private_));
}

::google::protobuf::Metadata MetaCacheEntry::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MetaCacheNode::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<MetaCacheNode>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_._has_bits_);
};

MetaCacheNode::MetaCacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MetaCacheNode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MetaCacheNode)
}
PROTOBUF_NDEBUG_INLINE MetaCacheNode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::MetaCacheNode& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        prev_(arena, from.prev_),
        next_(arena, from.next_) {}

MetaCacheNode::MetaCacheNode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MetaCacheNode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MetaCacheNode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MetaCacheNode* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.entry_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.entry_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:MetaCacheNode)
}
PROTOBUF_NDEBUG_INLINE MetaCacheNode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        prev_(arena),
        next_(arena) {}

inline void MetaCacheNode::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.entry_ = {};
}
MetaCacheNode::~MetaCacheNode() {
  // @@protoc_insertion_point(destructor:MetaCacheNode)
  SharedDtor(*this);
}
inline void MetaCacheNode::SharedDtor(MessageLite& self) {
  MetaCacheNode& this_ = static_cast<MetaCacheNode&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.prev_.Destroy();
  this_._impl_.next_.Destroy();
  delete this_._impl_.entry_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MetaCacheNode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MetaCacheNode(arena);
}
constexpr auto MetaCacheNode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MetaCacheNode),
                                            alignof(MetaCacheNode));
}
constexpr auto MetaCacheNode::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MetaCacheNode_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MetaCacheNode::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MetaCacheNode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MetaCacheNode::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MetaCacheNode>(), &MetaCacheNode::ByteSizeLong,
              &MetaCacheNode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_._cached_size_),
          false,
      },
      &MetaCacheNode::kDescriptorMethods,
      &descriptor_table_cache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MetaCacheNode_class_data_ =
        MetaCacheNode::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
MetaCacheNode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MetaCacheNode_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MetaCacheNode_class_data_.tc_table);
  return MetaCacheNode_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 30, 2>
MetaCacheNode::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    MetaCacheNode_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MetaCacheNode>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .MetaCacheEntry entry = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 2, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_.entry_)}},
    // string prev = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_.prev_)}},
    // string next = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_.next_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .MetaCacheEntry entry = 1;
    {PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_.entry_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string prev = 2;
    {PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_.prev_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string next = 3;
    {PROTOBUF_FIELD_OFFSET(MetaCacheNode, _impl_.next_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::MetaCacheEntry>()},
  }},
  {{
    "\15\0\4\4\0\0\0\0"
    "MetaCacheNode"
    "prev"
    "next"
  }},
};
PROTOBUF_NOINLINE void MetaCacheNode::Clear() {
// @@protoc_insertion_point(message_clear_start:MetaCacheNode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.prev_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.next_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.entry_ != nullptr);
      _impl_.entry_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MetaCacheNode::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MetaCacheNode& this_ = static_cast<const MetaCacheNode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MetaCacheNode::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MetaCacheNode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:MetaCacheNode)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .MetaCacheEntry entry = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.entry_, this_._impl_.entry_->GetCachedSize(), target,
        stream);
  }

  // string prev = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_prev();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MetaCacheNode.prev");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string next = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_next();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MetaCacheNode.next");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MetaCacheNode)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MetaCacheNode::ByteSizeLong(const MessageLite& base) {
  const MetaCacheNode& this_ = static_cast<const MetaCacheNode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MetaCacheNode::ByteSizeLong() const {
  const MetaCacheNode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:MetaCacheNode)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string prev = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_prev());
    }
    // string next = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_next());
    }
    // .MetaCacheEntry entry = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.entry_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MetaCacheNode::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<MetaCacheNode*>(&to_msg);
  auto& from = static_cast<const MetaCacheNode&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:MetaCacheNode)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_prev(from._internal_prev());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_next(from._internal_next());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.entry_ != nullptr);
      if (_this->_impl_.entry_ == nullptr) {
        _this->_impl_.entry_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.entry_);
      } else {
        _this->_impl_.entry_->MergeFrom(*from._impl_.entry_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void MetaCacheNode::CopyFrom(const MetaCacheNode& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:MetaCacheNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MetaCacheNode::InternalSwap(MetaCacheNode* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.prev_.InternalSwap(&_impl_.prev_, &other->_impl_.prev_, arena);
  _impl_.next_.InternalSwap(&_impl_.next_, &other->_impl_.next_, arena);
  swap(_impl_.entry_, other->_impl_.entry_);
}

::google::protobuf::Metadata MetaCacheNode::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_cache_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
