// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playlist_cache.proto
// Protobuf C++ Version: 6.33.5

#include "../include/playlist_cache.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr Playlist::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        etag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        short_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_private_{false},
        items_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Playlist::Playlist(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Playlist_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistDefaultTypeInternal() {}
  union {
    Playlist _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistDefaultTypeInternal _Playlist_default_instance_;

inline constexpr CacheHead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        next_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        etag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CacheHead::CacheHead(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CacheHead_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CacheHeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CacheHeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CacheHeadDefaultTypeInternal() {}
  union {
    CacheHead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CacheHeadDefaultTypeInternal _CacheHead_default_instance_;

inline constexpr CacheNode::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        next_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        playlist_{nullptr},
        is_tracked_{false} {}

template <typename>
PROTOBUF_CONSTEXPR CacheNode::CacheNode(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CacheNode_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CacheNodeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CacheNodeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CacheNodeDefaultTypeInternal() {}
  union {
    CacheNode _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CacheNodeDefaultTypeInternal _CacheNode_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_playlist_5fcache_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_playlist_5fcache_2eproto = nullptr;
const ::uint32_t
    TableStruct_playlist_5fcache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::CacheHead, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::CacheHead, _impl_.next_),
        PROTOBUF_FIELD_OFFSET(::proto::CacheHead, _impl_.etag_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_.etag_),
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_.is_private_),
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::proto::Playlist, _impl_.short_id_),
        0,
        1,
        2,
        4,
        5,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::CacheNode, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::CacheNode, _impl_.next_),
        PROTOBUF_FIELD_OFFSET(::proto::CacheNode, _impl_.playlist_),
        PROTOBUF_FIELD_OFFSET(::proto::CacheNode, _impl_.is_tracked_),
        PROTOBUF_FIELD_OFFSET(::proto::CacheNode, _impl_.id_hash_),
        0,
        2,
        3,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::CacheHead)},
        {7, sizeof(::proto::Playlist)},
        {22, sizeof(::proto::CacheNode)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_CacheHead_default_instance_._instance,
    &::proto::_Playlist_default_instance_._instance,
    &::proto::_CacheNode_default_instance_._instance,
};
const char descriptor_table_protodef_playlist_5fcache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024playlist_cache.proto\022\005proto\"\'\n\tCacheHe"
    "ad\022\014\n\004next\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\"h\n\010Playli"
    "st\022\n\n\002id\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\022\r\n\005title\030\003 "
    "\001(\t\022\022\n\nis_private\030\004 \001(\010\022\r\n\005items\030\005 \001(\005\022\020"
    "\n\010short_id\030\006 \001(\t\"a\n\tCacheNode\022\014\n\004next\030\001 "
    "\001(\t\022!\n\010playlist\030\002 \001(\0132\017.proto.Playlist\022\022"
    "\n\nis_tracked\030\003 \001(\010\022\017\n\007id_hash\030\004 \001(\014b\010edi"
    "tionsp\351\007"
};
static ::absl::once_flag descriptor_table_playlist_5fcache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_playlist_5fcache_2eproto = {
    false,
    false,
    288,
    descriptor_table_protodef_playlist_5fcache_2eproto,
    "playlist_cache.proto",
    &descriptor_table_playlist_5fcache_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_playlist_5fcache_2eproto::offsets,
    file_level_enum_descriptors_playlist_5fcache_2eproto,
    file_level_service_descriptors_playlist_5fcache_2eproto,
};
namespace proto {
// ===================================================================

class CacheHead::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CacheHead>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CacheHead, _impl_._has_bits_);
};

CacheHead::CacheHead(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheHead_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.CacheHead)
}
PROTOBUF_NDEBUG_INLINE CacheHead::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::CacheHead& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        next_(arena, from.next_),
        etag_(arena, from.etag_) {}

CacheHead::CacheHead(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CacheHead& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheHead_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CacheHead* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.CacheHead)
}
PROTOBUF_NDEBUG_INLINE CacheHead::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        next_(arena),
        etag_(arena) {}

inline void CacheHead::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CacheHead::~CacheHead() {
  // @@protoc_insertion_point(destructor:proto.CacheHead)
  SharedDtor(*this);
}
inline void CacheHead::SharedDtor(MessageLite& self) {
  CacheHead& this_ = static_cast<CacheHead&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.next_.Destroy();
  this_._impl_.etag_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CacheHead::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CacheHead(arena);
}
constexpr auto CacheHead::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CacheHead),
                                            alignof(CacheHead));
}
constexpr auto CacheHead::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CacheHead_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CacheHead::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CacheHead>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CacheHead::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CacheHead>(), &CacheHead::ByteSizeLong,
              &CacheHead::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CacheHead, _impl_._cached_size_),
          false,
      },
      &CacheHead::kDescriptorMethods,
      &descriptor_table_playlist_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CacheHead_class_data_ =
        CacheHead::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CacheHead::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CacheHead_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CacheHead_class_data_.tc_table);
  return CacheHead_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2>
CacheHead::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CacheHead, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CacheHead_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::CacheHead>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string etag = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(CacheHead, _impl_.etag_)}},
    // string next = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CacheHead, _impl_.next_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string next = 1;
    {PROTOBUF_FIELD_OFFSET(CacheHead, _impl_.next_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string etag = 2;
    {PROTOBUF_FIELD_OFFSET(CacheHead, _impl_.etag_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\4\4\0\0\0\0\0"
    "proto.CacheHead"
    "next"
    "etag"
  }},
};
PROTOBUF_NOINLINE void CacheHead::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.CacheHead)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.next_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.etag_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CacheHead::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CacheHead& this_ = static_cast<const CacheHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CacheHead::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CacheHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.CacheHead)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string next = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_next();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.CacheHead.next");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string etag = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_etag();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.CacheHead.etag");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.CacheHead)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CacheHead::ByteSizeLong(const MessageLite& base) {
  const CacheHead& this_ = static_cast<const CacheHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CacheHead::ByteSizeLong() const {
  const CacheHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.CacheHead)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string next = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_next());
    }
    // string etag = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_etag());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CacheHead::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CacheHead*>(&to_msg);
  auto& from = static_cast<const CacheHead&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.CacheHead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_next(from._internal_next());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_etag(from._internal_etag());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CacheHead::CopyFrom(const CacheHead& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.CacheHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CacheHead::InternalSwap(CacheHead* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.next_.InternalSwap(&_impl_.next_, &other->_impl_.next_, arena);
  _impl_.etag_.InternalSwap(&_impl_.etag_, &other->_impl_.etag_, arena);
}

::google::protobuf::Metadata CacheHead::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Playlist::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Playlist>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Playlist, _impl_._has_bits_);
};

Playlist::Playlist(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Playlist_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.Playlist)
}
PROTOBUF_NDEBUG_INLINE Playlist::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::Playlist& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        etag_(arena, from.etag_),
        title_(arena, from.title_),
        short_id_(arena, from.short_id_) {}

Playlist::Playlist(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Playlist& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Playlist_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Playlist* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_private_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, is_private_),
           offsetof(Impl_, items_) -
               offsetof(Impl_, is_private_) +
               sizeof(Impl_::items_));

  // @@protoc_insertion_point(copy_constructor:proto.Playlist)
}
PROTOBUF_NDEBUG_INLINE Playlist::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        etag_(arena),
        title_(arena),
        short_id_(arena) {}

inline void Playlist::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, is_private_),
           0,
           offsetof(Impl_, items_) -
               offsetof(Impl_, is_private_) +
               sizeof(Impl_::items_));
}
Playlist::~Playlist() {
  // @@protoc_insertion_point(destructor:proto.Playlist)
  SharedDtor(*this);
}
inline void Playlist::SharedDtor(MessageLite& self) {
  Playlist& this_ = static_cast<Playlist&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.etag_.Destroy();
  this_._impl_.title_.Destroy();
  this_._impl_.short_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Playlist::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Playlist(arena);
}
constexpr auto Playlist::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Playlist),
                                            alignof(Playlist));
}
constexpr auto Playlist::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Playlist_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Playlist::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Playlist>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Playlist::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Playlist>(), &Playlist::ByteSizeLong,
              &Playlist::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Playlist, _impl_._cached_size_),
          false,
      },
      &Playlist::kDescriptorMethods,
      &descriptor_table_playlist_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Playlist_class_data_ =
        Playlist::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Playlist::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Playlist_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Playlist_class_data_.tc_table);
  return Playlist_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 42, 2>
Playlist::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Playlist, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Playlist_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::Playlist>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.id_)}},
    // string etag = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.etag_)}},
    // string title = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.title_)}},
    // bool is_private = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Playlist, _impl_.is_private_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.is_private_)}},
    // int32 items = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Playlist, _impl_.items_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.items_)}},
    // string short_id = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 3, 0,
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.short_id_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(Playlist, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string etag = 2;
    {PROTOBUF_FIELD_OFFSET(Playlist, _impl_.etag_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string title = 3;
    {PROTOBUF_FIELD_OFFSET(Playlist, _impl_.title_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool is_private = 4;
    {PROTOBUF_FIELD_OFFSET(Playlist, _impl_.is_private_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // int32 items = 5;
    {PROTOBUF_FIELD_OFFSET(Playlist, _impl_.items_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string short_id = 6;
    {PROTOBUF_FIELD_OFFSET(Playlist, _impl_.short_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\2\4\5\0\0\10\0"
    "proto.Playlist"
    "id"
    "etag"
    "title"
    "short_id"
  }},
};
PROTOBUF_NOINLINE void Playlist::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Playlist)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.etag_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.short_id_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000030U)) {
    ::memset(&_impl_.is_private_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.items_) -
        reinterpret_cast<char*>(&_impl_.is_private_)) + sizeof(_impl_.items_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Playlist::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Playlist& this_ = static_cast<const Playlist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Playlist::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Playlist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.Playlist)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.Playlist.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string etag = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_etag();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.Playlist.etag");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string title = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::absl::string_view _s = this_._internal_title();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.Playlist.title");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bool is_private = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_is_private(), target);
  }

  // int32 items = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_items(), target);
  }

  // string short_id = 6;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::absl::string_view _s = this_._internal_short_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.Playlist.short_id");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.Playlist)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Playlist::ByteSizeLong(const MessageLite& base) {
  const Playlist& this_ = static_cast<const Playlist&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Playlist::ByteSizeLong() const {
  const Playlist& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.Playlist)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000010U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x0000002fU)) {
    // string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
    // string etag = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_etag());
    }
    // string title = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_title());
    }
    // string short_id = 6;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_short_id());
    }
    // int32 items = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_items());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Playlist::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Playlist*>(&to_msg);
  auto& from = static_cast<const Playlist&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.Playlist)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_id(from._internal_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_etag(from._internal_etag());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_title(from._internal_title());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_short_id(from._internal_short_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.is_private_ = from._impl_.is_private_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.items_ = from._impl_.items_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Playlist::CopyFrom(const Playlist& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.Playlist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Playlist::InternalSwap(Playlist* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.id_.InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  _impl_.etag_.InternalSwap(&_impl_.etag_, &other->_impl_.etag_, arena);
  _impl_.title_.InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  _impl_.short_id_.InternalSwap(&_impl_.short_id_, &other->_impl_.short_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Playlist, _impl_.items_)
      + sizeof(Playlist::_impl_.items_)
      - PROTOBUF_FIELD_OFFSET(Playlist, _impl_.is_private_)>(
          reinterpret_cast<char*>(&_impl_.is_private_),
          reinterpret_cast<char*>(&other->_impl_.is_private_));
}

::google::protobuf::Metadata Playlist::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CacheNode::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CacheNode>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CacheNode, _impl_._has_bits_);
};

CacheNode::CacheNode(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheNode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.CacheNode)
}
PROTOBUF_NDEBUG_INLINE CacheNode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::CacheNode& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        next_(arena, from.next_),
        id_hash_(arena, from.id_hash_) {}

CacheNode::CacheNode(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CacheNode& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CacheNode_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CacheNode* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.playlist_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.playlist_)
                : nullptr;
  _impl_.is_tracked_ = from._impl_.is_tracked_;

  // @@protoc_insertion_point(copy_constructor:proto.CacheNode)
}
PROTOBUF_NDEBUG_INLINE CacheNode::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        next_(arena),
        id_hash_(arena) {}

inline void CacheNode::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, playlist_),
           0,
           offsetof(Impl_, is_tracked_) -
               offsetof(Impl_, playlist_) +
               sizeof(Impl_::is_tracked_));
}
CacheNode::~CacheNode() {
  // @@protoc_insertion_point(destructor:proto.CacheNode)
  SharedDtor(*this);
}
inline void CacheNode::SharedDtor(MessageLite& self) {
  CacheNode& this_ = static_cast<CacheNode&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.next_.Destroy();
  this_._impl_.id_hash_.Destroy();
  delete this_._impl_.playlist_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CacheNode::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CacheNode(arena);
}
constexpr auto CacheNode::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CacheNode),
                                            alignof(CacheNode));
}
constexpr auto CacheNode::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CacheNode_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CacheNode::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CacheNode>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CacheNode::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CacheNode>(), &CacheNode::ByteSizeLong,
              &CacheNode::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CacheNode, _impl_._cached_size_),
          false,
      },
      &CacheNode::kDescriptorMethods,
      &descriptor_table_playlist_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CacheNode_class_data_ =
        CacheNode::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CacheNode::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CacheNode_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CacheNode_class_data_.tc_table);
  return CacheNode_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 28, 2>
CacheNode::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CacheNode, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CacheNode_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::CacheNode>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes id_hash = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.id_hash_)}},
    // string next = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.next_)}},
    // .proto.Playlist playlist = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 2, 0,
      PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.playlist_)}},
    // bool is_tracked = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CacheNode, _impl_.is_tracked_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.is_tracked_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string next = 1;
    {PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.next_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .proto.Playlist playlist = 2;
    {PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.playlist_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool is_tracked = 3;
    {PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.is_tracked_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bytes id_hash = 4;
    {PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.id_hash_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::Playlist>()},
  }},
  {{
    "\17\4\0\0\0\0\0\0"
    "proto.CacheNode"
    "next"
  }},
};
PROTOBUF_NOINLINE void CacheNode::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.CacheNode)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.next_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.id_hash_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.playlist_ != nullptr);
      _impl_.playlist_->Clear();
    }
  }
  _impl_.is_tracked_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CacheNode::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CacheNode& this_ = static_cast<const CacheNode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CacheNode::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CacheNode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.CacheNode)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string next = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_next();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.CacheNode.next");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // .proto.Playlist playlist = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.playlist_, this_._impl_.playlist_->GetCachedSize(), target,
        stream);
  }

  // bool is_tracked = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this_._internal_is_tracked(), target);
  }

  // bytes id_hash = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_id_hash();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.CacheNode)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CacheNode::ByteSizeLong(const MessageLite& base) {
  const CacheNode& this_ = static_cast<const CacheNode&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CacheNode::ByteSizeLong() const {
  const CacheNode& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.CacheNode)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000008U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string next = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_next());
    }
    // bytes id_hash = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_id_hash());
    }
    // .proto.Playlist playlist = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.playlist_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CacheNode::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CacheNode*>(&to_msg);
  auto& from = static_cast<const CacheNode&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.CacheNode)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_next(from._internal_next());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_id_hash(from._internal_id_hash());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.playlist_ != nullptr);
      if (_this->_impl_.playlist_ == nullptr) {
        _this->_impl_.playlist_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.playlist_);
      } else {
        _this->_impl_.playlist_->MergeFrom(*from._impl_.playlist_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.is_tracked_ = from._impl_.is_tracked_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CacheNode::CopyFrom(const CacheNode& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.CacheNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CacheNode::InternalSwap(CacheNode* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.next_.InternalSwap(&_impl_.next_, &other->_impl_.next_, arena);
  _impl_.id_hash_.InternalSwap(&_impl_.id_hash_, &other->_impl_.id_hash_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.is_tracked_)
      + sizeof(CacheNode::_impl_.is_tracked_)
      - PROTOBUF_FIELD_OFFSET(CacheNode, _impl_.playlist_)>(
          reinterpret_cast<char*>(&_impl_.playlist_),
          reinterpret_cast<char*>(&other->_impl_.playlist_));
}

::google::protobuf::Metadata CacheNode::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_playlist_5fcache_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
