// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: playlist_items_cache.proto
// Protobuf C++ Version: 6.33.5

#include "../include/playlist_items_cache.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr PlaylistInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        items_etag_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        plat_{static_cast< ::proto::Platform >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistInfo::PlaylistInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistInfo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistInfoDefaultTypeInternal() {}
  union {
    PlaylistInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistInfoDefaultTypeInternal _PlaylistInfo_default_instance_;

inline constexpr PlaylistItems::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tracked_playlists_{},
        song_hashes_{} {}

template <typename>
PROTOBUF_CONSTEXPR PlaylistItems::PlaylistItems(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PlaylistItems_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PlaylistItemsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlaylistItemsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlaylistItemsDefaultTypeInternal() {}
  union {
    PlaylistItems _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlaylistItemsDefaultTypeInternal _PlaylistItems_default_instance_;
}  // namespace proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_playlist_5fitems_5fcache_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_playlist_5fitems_5fcache_2eproto = nullptr;
const ::uint32_t
    TableStruct_playlist_5fitems_5fcache_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistInfo, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistInfo, _impl_.plat_),
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistInfo, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistInfo, _impl_.items_etag_),
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistInfo, _impl_.title_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistItems, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistItems, _impl_.tracked_playlists_),
        PROTOBUF_FIELD_OFFSET(::proto::PlaylistItems, _impl_.song_hashes_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::PlaylistInfo)},
        {11, sizeof(::proto::PlaylistItems)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_PlaylistInfo_default_instance_._instance,
    &::proto::_PlaylistItems_default_instance_._instance,
};
const char descriptor_table_protodef_playlist_5fitems_5fcache_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\032playlist_items_cache.proto\022\005proto\"\\\n\014P"
    "laylistInfo\022\035\n\004plat\030\001 \001(\0162\017.proto.Platfo"
    "rm\022\n\n\002id\030\002 \001(\t\022\022\n\nitems_etag\030\003 \001(\t\022\r\n\005ti"
    "tle\030\004 \001(\t\"T\n\rPlaylistItems\022.\n\021tracked_pl"
    "aylists\030\001 \003(\0132\023.proto.PlaylistInfo\022\023\n\013so"
    "ng_hashes\030\002 \003(\014*1\n\010Platform\022\013\n\007YOUTUBE\020\000"
    "\022\013\n\007SPOTIFY\020\001\022\013\n\007INVALID\020\002b\010editionsp\351\007"
};
static ::absl::once_flag descriptor_table_playlist_5fitems_5fcache_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_playlist_5fitems_5fcache_2eproto = {
    false,
    false,
    279,
    descriptor_table_protodef_playlist_5fitems_5fcache_2eproto,
    "playlist_items_cache.proto",
    &descriptor_table_playlist_5fitems_5fcache_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_playlist_5fitems_5fcache_2eproto::offsets,
    file_level_enum_descriptors_playlist_5fitems_5fcache_2eproto,
    file_level_service_descriptors_playlist_5fitems_5fcache_2eproto,
};
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Platform_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_playlist_5fitems_5fcache_2eproto);
  return file_level_enum_descriptors_playlist_5fitems_5fcache_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Platform_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class PlaylistInfo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistInfo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_._has_bits_);
};

PlaylistInfo::PlaylistInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.PlaylistInfo)
}
PROTOBUF_NDEBUG_INLINE PlaylistInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::PlaylistInfo& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        items_etag_(arena, from.items_etag_),
        title_(arena, from.title_) {}

PlaylistInfo::PlaylistInfo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaylistInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistInfo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaylistInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.plat_ = from._impl_.plat_;

  // @@protoc_insertion_point(copy_constructor:proto.PlaylistInfo)
}
PROTOBUF_NDEBUG_INLINE PlaylistInfo::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        items_etag_(arena),
        title_(arena) {}

inline void PlaylistInfo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.plat_ = {};
}
PlaylistInfo::~PlaylistInfo() {
  // @@protoc_insertion_point(destructor:proto.PlaylistInfo)
  SharedDtor(*this);
}
inline void PlaylistInfo::SharedDtor(MessageLite& self) {
  PlaylistInfo& this_ = static_cast<PlaylistInfo&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.items_etag_.Destroy();
  this_._impl_.title_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistInfo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistInfo(arena);
}
constexpr auto PlaylistInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PlaylistInfo),
                                            alignof(PlaylistInfo));
}
constexpr auto PlaylistInfo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistInfo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistInfo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistInfo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistInfo>(), &PlaylistInfo::ByteSizeLong,
              &PlaylistInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_._cached_size_),
          false,
      },
      &PlaylistInfo::kDescriptorMethods,
      &descriptor_table_playlist_5fitems_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistInfo_class_data_ =
        PlaylistInfo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistInfo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistInfo_class_data_.tc_table);
  return PlaylistInfo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 44, 2>
PlaylistInfo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PlaylistInfo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::PlaylistInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string title = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.title_)}},
    // .proto.Platform plat = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PlaylistInfo, _impl_.plat_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.plat_)}},
    // string id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.id_)}},
    // string items_etag = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.items_etag_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .proto.Platform plat = 1;
    {PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.plat_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string id = 2;
    {PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string items_etag = 3;
    {PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.items_etag_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string title = 4;
    {PROTOBUF_FIELD_OFFSET(PlaylistInfo, _impl_.title_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\2\12\5\0\0\0"
    "proto.PlaylistInfo"
    "id"
    "items_etag"
    "title"
  }},
};
PROTOBUF_NOINLINE void PlaylistInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.PlaylistInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.items_etag_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.title_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.plat_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistInfo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistInfo& this_ = static_cast<const PlaylistInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistInfo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.PlaylistInfo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .proto.Platform plat = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_plat(), target);
  }

  // string id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.PlaylistInfo.id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string items_etag = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_items_etag();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.PlaylistInfo.items_etag");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string title = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::absl::string_view _s = this_._internal_title();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.PlaylistInfo.title");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.PlaylistInfo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistInfo::ByteSizeLong(const MessageLite& base) {
  const PlaylistInfo& this_ = static_cast<const PlaylistInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistInfo::ByteSizeLong() const {
  const PlaylistInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.PlaylistInfo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
    // string items_etag = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_items_etag());
    }
    // string title = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_title());
    }
    // .proto.Platform plat = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_plat());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistInfo::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistInfo*>(&to_msg);
  auto& from = static_cast<const PlaylistInfo&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.PlaylistInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_id(from._internal_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_items_etag(from._internal_items_etag());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_title(from._internal_title());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.plat_ = from._impl_.plat_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistInfo::CopyFrom(const PlaylistInfo& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.PlaylistInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistInfo::InternalSwap(PlaylistInfo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.id_.InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  _impl_.items_etag_.InternalSwap(&_impl_.items_etag_, &other->_impl_.items_etag_, arena);
  _impl_.title_.InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  swap(_impl_.plat_, other->_impl_.plat_);
}

::google::protobuf::Metadata PlaylistInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PlaylistItems::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PlaylistItems>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_._has_bits_);
};

PlaylistItems::PlaylistItems(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistItems_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.PlaylistItems)
}
PROTOBUF_NDEBUG_INLINE PlaylistItems::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::PlaylistItems& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tracked_playlists_{visibility, arena, from.tracked_playlists_},
        song_hashes_{visibility, arena, from.song_hashes_} {}

PlaylistItems::PlaylistItems(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PlaylistItems& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PlaylistItems_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PlaylistItems* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.PlaylistItems)
}
PROTOBUF_NDEBUG_INLINE PlaylistItems::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tracked_playlists_{visibility, arena},
        song_hashes_{visibility, arena} {}

inline void PlaylistItems::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PlaylistItems::~PlaylistItems() {
  // @@protoc_insertion_point(destructor:proto.PlaylistItems)
  SharedDtor(*this);
}
inline void PlaylistItems::SharedDtor(MessageLite& self) {
  PlaylistItems& this_ = static_cast<PlaylistItems&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PlaylistItems::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PlaylistItems(arena);
}
constexpr auto PlaylistItems::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_.tracked_playlists_) +
          decltype(PlaylistItems::_impl_.tracked_playlists_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_.song_hashes_) +
          decltype(PlaylistItems::_impl_.song_hashes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PlaylistItems), alignof(PlaylistItems), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PlaylistItems::PlacementNew_,
                                 sizeof(PlaylistItems),
                                 alignof(PlaylistItems));
  }
}
constexpr auto PlaylistItems::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PlaylistItems_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PlaylistItems::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PlaylistItems>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PlaylistItems::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PlaylistItems>(), &PlaylistItems::ByteSizeLong,
              &PlaylistItems::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_._cached_size_),
          false,
      },
      &PlaylistItems::kDescriptorMethods,
      &descriptor_table_playlist_5fitems_5fcache_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PlaylistItems_class_data_ =
        PlaylistItems::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PlaylistItems::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PlaylistItems_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PlaylistItems_class_data_.tc_table);
  return PlaylistItems_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2>
PlaylistItems::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PlaylistItems_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::PlaylistItems>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated bytes song_hashes = 2;
    {::_pbi::TcParser::FastBR1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_.song_hashes_)}},
    // repeated .proto.PlaylistInfo tracked_playlists = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_.tracked_playlists_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .proto.PlaylistInfo tracked_playlists = 1;
    {PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_.tracked_playlists_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated bytes song_hashes = 2;
    {PROTOBUF_FIELD_OFFSET(PlaylistItems, _impl_.song_hashes_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::PlaylistInfo>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PlaylistItems::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.PlaylistItems)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.tracked_playlists_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.song_hashes_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PlaylistItems::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PlaylistItems& this_ = static_cast<const PlaylistItems&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PlaylistItems::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PlaylistItems& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.PlaylistItems)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .proto.PlaylistInfo tracked_playlists = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_tracked_playlists_size());
         i < n; i++) {
      const auto& repfield = this_._internal_tracked_playlists().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated bytes song_hashes = 2;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (int i = 0, n = this_._internal_song_hashes_size(); i < n; ++i) {
      const auto& s = this_._internal_song_hashes().Get(i);
      target = stream->WriteBytes(2, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.PlaylistItems)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PlaylistItems::ByteSizeLong(const MessageLite& base) {
  const PlaylistItems& this_ = static_cast<const PlaylistItems&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PlaylistItems::ByteSizeLong() const {
  const PlaylistItems& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.PlaylistItems)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // repeated .proto.PlaylistInfo tracked_playlists = 1;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_tracked_playlists_size();
      for (const auto& msg : this_._internal_tracked_playlists()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated bytes song_hashes = 2;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_song_hashes().size());
      for (int i = 0, n = this_._internal_song_hashes().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_song_hashes().Get(i));
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PlaylistItems::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PlaylistItems*>(&to_msg);
  auto& from = static_cast<const PlaylistItems&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.PlaylistItems)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_tracked_playlists()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_tracked_playlists());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_song_hashes()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_song_hashes());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PlaylistItems::CopyFrom(const PlaylistItems& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.PlaylistItems)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PlaylistItems::InternalSwap(PlaylistItems* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.tracked_playlists_.InternalSwap(&other->_impl_.tracked_playlists_);
  _impl_.song_hashes_.InternalSwap(&other->_impl_.song_hashes_);
}

::google::protobuf::Metadata PlaylistItems::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_playlist_5fitems_5fcache_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
