// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sid_to_id_map.proto
// Protobuf C++ Version: 6.33.5

#include "../include/sid_to_id_map.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr SidToIdMap_Pair::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        short_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR SidToIdMap_Pair::SidToIdMap_Pair(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SidToIdMap_Pair_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SidToIdMap_PairDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SidToIdMap_PairDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SidToIdMap_PairDefaultTypeInternal() {}
  union {
    SidToIdMap_Pair _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SidToIdMap_PairDefaultTypeInternal _SidToIdMap_Pair_default_instance_;

inline constexpr SidToIdMap_Bucket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pairs_{} {}

template <typename>
PROTOBUF_CONSTEXPR SidToIdMap_Bucket::SidToIdMap_Bucket(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SidToIdMap_Bucket_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SidToIdMap_BucketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SidToIdMap_BucketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SidToIdMap_BucketDefaultTypeInternal() {}
  union {
    SidToIdMap_Bucket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SidToIdMap_BucketDefaultTypeInternal _SidToIdMap_Bucket_default_instance_;

inline constexpr SidToIdMap::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        buckets_{} {}

template <typename>
PROTOBUF_CONSTEXPR SidToIdMap::SidToIdMap(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SidToIdMap_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SidToIdMapDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SidToIdMapDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SidToIdMapDefaultTypeInternal() {}
  union {
    SidToIdMap _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SidToIdMapDefaultTypeInternal _SidToIdMap_default_instance_;
}  // namespace proto
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_sid_5fto_5fid_5fmap_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_sid_5fto_5fid_5fmap_2eproto = nullptr;
const ::uint32_t
    TableStruct_sid_5fto_5fid_5fmap_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap_Pair, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap_Pair, _impl_.short_id_),
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap_Pair, _impl_.id_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap_Bucket, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap_Bucket, _impl_.pairs_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SidToIdMap, _impl_.buckets_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::SidToIdMap_Pair)},
        {7, sizeof(::proto::SidToIdMap_Bucket)},
        {12, sizeof(::proto::SidToIdMap)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_SidToIdMap_Pair_default_instance_._instance,
    &::proto::_SidToIdMap_Bucket_default_instance_._instance,
    &::proto::_SidToIdMap_default_instance_._instance,
};
const char descriptor_table_protodef_sid_5fto_5fid_5fmap_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023sid_to_id_map.proto\022\005proto\"\216\001\n\nSidToId"
    "Map\022)\n\007buckets\030\001 \003(\0132\030.proto.SidToIdMap."
    "Bucket\032$\n\004Pair\022\020\n\010short_id\030\001 \001(\014\022\n\n\002id\030\002"
    " \001(\t\032/\n\006Bucket\022%\n\005pairs\030\001 \003(\0132\026.proto.Si"
    "dToIdMap.Pairb\010editionsp\351\007"
};
static ::absl::once_flag descriptor_table_sid_5fto_5fid_5fmap_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sid_5fto_5fid_5fmap_2eproto = {
    false,
    false,
    186,
    descriptor_table_protodef_sid_5fto_5fid_5fmap_2eproto,
    "sid_to_id_map.proto",
    &descriptor_table_sid_5fto_5fid_5fmap_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_sid_5fto_5fid_5fmap_2eproto::offsets,
    file_level_enum_descriptors_sid_5fto_5fid_5fmap_2eproto,
    file_level_service_descriptors_sid_5fto_5fid_5fmap_2eproto,
};
namespace proto {
// ===================================================================

class SidToIdMap_Pair::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SidToIdMap_Pair>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_._has_bits_);
};

SidToIdMap_Pair::SidToIdMap_Pair(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidToIdMap_Pair_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SidToIdMap.Pair)
}
PROTOBUF_NDEBUG_INLINE SidToIdMap_Pair::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::SidToIdMap_Pair& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        short_id_(arena, from.short_id_),
        id_(arena, from.id_) {}

SidToIdMap_Pair::SidToIdMap_Pair(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SidToIdMap_Pair& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidToIdMap_Pair_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SidToIdMap_Pair* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.SidToIdMap.Pair)
}
PROTOBUF_NDEBUG_INLINE SidToIdMap_Pair::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        short_id_(arena),
        id_(arena) {}

inline void SidToIdMap_Pair::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SidToIdMap_Pair::~SidToIdMap_Pair() {
  // @@protoc_insertion_point(destructor:proto.SidToIdMap.Pair)
  SharedDtor(*this);
}
inline void SidToIdMap_Pair::SharedDtor(MessageLite& self) {
  SidToIdMap_Pair& this_ = static_cast<SidToIdMap_Pair&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.short_id_.Destroy();
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SidToIdMap_Pair::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SidToIdMap_Pair(arena);
}
constexpr auto SidToIdMap_Pair::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SidToIdMap_Pair),
                                            alignof(SidToIdMap_Pair));
}
constexpr auto SidToIdMap_Pair::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SidToIdMap_Pair_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SidToIdMap_Pair::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SidToIdMap_Pair>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SidToIdMap_Pair::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SidToIdMap_Pair>(), &SidToIdMap_Pair::ByteSizeLong,
              &SidToIdMap_Pair::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_._cached_size_),
          false,
      },
      &SidToIdMap_Pair::kDescriptorMethods,
      &descriptor_table_sid_5fto_5fid_5fmap_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SidToIdMap_Pair_class_data_ =
        SidToIdMap_Pair::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SidToIdMap_Pair::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SidToIdMap_Pair_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SidToIdMap_Pair_class_data_.tc_table);
  return SidToIdMap_Pair_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2>
SidToIdMap_Pair::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SidToIdMap_Pair_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SidToIdMap_Pair>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_.id_)}},
    // bytes short_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_.short_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes short_id = 1;
    {PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_.short_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // string id = 2;
    {PROTOBUF_FIELD_OFFSET(SidToIdMap_Pair, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\0\2\0\0\0\0\0"
    "proto.SidToIdMap.Pair"
    "id"
  }},
};
PROTOBUF_NOINLINE void SidToIdMap_Pair::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SidToIdMap.Pair)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.short_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SidToIdMap_Pair::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SidToIdMap_Pair& this_ = static_cast<const SidToIdMap_Pair&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SidToIdMap_Pair::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SidToIdMap_Pair& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SidToIdMap.Pair)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes short_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::absl::string_view _s = this_._internal_short_id();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // string id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::absl::string_view _s = this_._internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "proto.SidToIdMap.Pair.id");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SidToIdMap.Pair)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SidToIdMap_Pair::ByteSizeLong(const MessageLite& base) {
  const SidToIdMap_Pair& this_ = static_cast<const SidToIdMap_Pair&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SidToIdMap_Pair::ByteSizeLong() const {
  const SidToIdMap_Pair& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SidToIdMap.Pair)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes short_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_short_id());
    }
    // string id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SidToIdMap_Pair::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SidToIdMap_Pair*>(&to_msg);
  auto& from = static_cast<const SidToIdMap_Pair&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SidToIdMap.Pair)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_short_id(from._internal_short_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_id(from._internal_id());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SidToIdMap_Pair::CopyFrom(const SidToIdMap_Pair& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SidToIdMap.Pair)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SidToIdMap_Pair::InternalSwap(SidToIdMap_Pair* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.short_id_.InternalSwap(&_impl_.short_id_, &other->_impl_.short_id_, arena);
  _impl_.id_.InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
}

::google::protobuf::Metadata SidToIdMap_Pair::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SidToIdMap_Bucket::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SidToIdMap_Bucket>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SidToIdMap_Bucket, _impl_._has_bits_);
};

SidToIdMap_Bucket::SidToIdMap_Bucket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidToIdMap_Bucket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SidToIdMap.Bucket)
}
PROTOBUF_NDEBUG_INLINE SidToIdMap_Bucket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::SidToIdMap_Bucket& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pairs_{visibility, arena, from.pairs_} {}

SidToIdMap_Bucket::SidToIdMap_Bucket(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SidToIdMap_Bucket& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidToIdMap_Bucket_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SidToIdMap_Bucket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.SidToIdMap.Bucket)
}
PROTOBUF_NDEBUG_INLINE SidToIdMap_Bucket::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pairs_{visibility, arena} {}

inline void SidToIdMap_Bucket::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SidToIdMap_Bucket::~SidToIdMap_Bucket() {
  // @@protoc_insertion_point(destructor:proto.SidToIdMap.Bucket)
  SharedDtor(*this);
}
inline void SidToIdMap_Bucket::SharedDtor(MessageLite& self) {
  SidToIdMap_Bucket& this_ = static_cast<SidToIdMap_Bucket&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SidToIdMap_Bucket::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SidToIdMap_Bucket(arena);
}
constexpr auto SidToIdMap_Bucket::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SidToIdMap_Bucket, _impl_.pairs_) +
          decltype(SidToIdMap_Bucket::_impl_.pairs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SidToIdMap_Bucket), alignof(SidToIdMap_Bucket), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SidToIdMap_Bucket::PlacementNew_,
                                 sizeof(SidToIdMap_Bucket),
                                 alignof(SidToIdMap_Bucket));
  }
}
constexpr auto SidToIdMap_Bucket::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SidToIdMap_Bucket_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SidToIdMap_Bucket::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SidToIdMap_Bucket>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SidToIdMap_Bucket::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SidToIdMap_Bucket>(), &SidToIdMap_Bucket::ByteSizeLong,
              &SidToIdMap_Bucket::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SidToIdMap_Bucket, _impl_._cached_size_),
          false,
      },
      &SidToIdMap_Bucket::kDescriptorMethods,
      &descriptor_table_sid_5fto_5fid_5fmap_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SidToIdMap_Bucket_class_data_ =
        SidToIdMap_Bucket::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SidToIdMap_Bucket::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SidToIdMap_Bucket_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SidToIdMap_Bucket_class_data_.tc_table);
  return SidToIdMap_Bucket_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
SidToIdMap_Bucket::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SidToIdMap_Bucket, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SidToIdMap_Bucket_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SidToIdMap_Bucket>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .proto.SidToIdMap.Pair pairs = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SidToIdMap_Bucket, _impl_.pairs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .proto.SidToIdMap.Pair pairs = 1;
    {PROTOBUF_FIELD_OFFSET(SidToIdMap_Bucket, _impl_.pairs_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::SidToIdMap_Pair>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SidToIdMap_Bucket::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SidToIdMap.Bucket)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.pairs_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SidToIdMap_Bucket::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SidToIdMap_Bucket& this_ = static_cast<const SidToIdMap_Bucket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SidToIdMap_Bucket::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SidToIdMap_Bucket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SidToIdMap.Bucket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .proto.SidToIdMap.Pair pairs = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_pairs_size());
         i < n; i++) {
      const auto& repfield = this_._internal_pairs().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SidToIdMap.Bucket)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SidToIdMap_Bucket::ByteSizeLong(const MessageLite& base) {
  const SidToIdMap_Bucket& this_ = static_cast<const SidToIdMap_Bucket&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SidToIdMap_Bucket::ByteSizeLong() const {
  const SidToIdMap_Bucket& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SidToIdMap.Bucket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .proto.SidToIdMap.Pair pairs = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_pairs_size();
      for (const auto& msg : this_._internal_pairs()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SidToIdMap_Bucket::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SidToIdMap_Bucket*>(&to_msg);
  auto& from = static_cast<const SidToIdMap_Bucket&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SidToIdMap.Bucket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_pairs()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_pairs());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SidToIdMap_Bucket::CopyFrom(const SidToIdMap_Bucket& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SidToIdMap.Bucket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SidToIdMap_Bucket::InternalSwap(SidToIdMap_Bucket* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pairs_.InternalSwap(&other->_impl_.pairs_);
}

::google::protobuf::Metadata SidToIdMap_Bucket::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SidToIdMap::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SidToIdMap>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SidToIdMap, _impl_._has_bits_);
};

SidToIdMap::SidToIdMap(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidToIdMap_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SidToIdMap)
}
PROTOBUF_NDEBUG_INLINE SidToIdMap::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::SidToIdMap& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        buckets_{visibility, arena, from.buckets_} {}

SidToIdMap::SidToIdMap(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SidToIdMap& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SidToIdMap_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SidToIdMap* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.SidToIdMap)
}
PROTOBUF_NDEBUG_INLINE SidToIdMap::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        buckets_{visibility, arena} {}

inline void SidToIdMap::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SidToIdMap::~SidToIdMap() {
  // @@protoc_insertion_point(destructor:proto.SidToIdMap)
  SharedDtor(*this);
}
inline void SidToIdMap::SharedDtor(MessageLite& self) {
  SidToIdMap& this_ = static_cast<SidToIdMap&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SidToIdMap::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SidToIdMap(arena);
}
constexpr auto SidToIdMap::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SidToIdMap, _impl_.buckets_) +
          decltype(SidToIdMap::_impl_.buckets_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SidToIdMap), alignof(SidToIdMap), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SidToIdMap::PlacementNew_,
                                 sizeof(SidToIdMap),
                                 alignof(SidToIdMap));
  }
}
constexpr auto SidToIdMap::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SidToIdMap_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SidToIdMap::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SidToIdMap>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SidToIdMap::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SidToIdMap>(), &SidToIdMap::ByteSizeLong,
              &SidToIdMap::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SidToIdMap, _impl_._cached_size_),
          false,
      },
      &SidToIdMap::kDescriptorMethods,
      &descriptor_table_sid_5fto_5fid_5fmap_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SidToIdMap_class_data_ =
        SidToIdMap::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SidToIdMap::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SidToIdMap_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SidToIdMap_class_data_.tc_table);
  return SidToIdMap_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
SidToIdMap::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SidToIdMap, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    SidToIdMap_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SidToIdMap>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .proto.SidToIdMap.Bucket buckets = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(SidToIdMap, _impl_.buckets_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .proto.SidToIdMap.Bucket buckets = 1;
    {PROTOBUF_FIELD_OFFSET(SidToIdMap, _impl_.buckets_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::proto::SidToIdMap_Bucket>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void SidToIdMap::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SidToIdMap)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.buckets_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SidToIdMap::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SidToIdMap& this_ = static_cast<const SidToIdMap&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SidToIdMap::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SidToIdMap& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SidToIdMap)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .proto.SidToIdMap.Bucket buckets = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_buckets_size());
         i < n; i++) {
      const auto& repfield = this_._internal_buckets().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SidToIdMap)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SidToIdMap::ByteSizeLong(const MessageLite& base) {
  const SidToIdMap& this_ = static_cast<const SidToIdMap&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SidToIdMap::ByteSizeLong() const {
  const SidToIdMap& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SidToIdMap)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .proto.SidToIdMap.Bucket buckets = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_buckets_size();
      for (const auto& msg : this_._internal_buckets()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SidToIdMap::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SidToIdMap*>(&to_msg);
  auto& from = static_cast<const SidToIdMap&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SidToIdMap)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_buckets()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_buckets());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SidToIdMap::CopyFrom(const SidToIdMap& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SidToIdMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SidToIdMap::InternalSwap(SidToIdMap* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.buckets_.InternalSwap(&other->_impl_.buckets_);
}

::google::protobuf::Metadata SidToIdMap::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_sid_5fto_5fid_5fmap_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
